[package]
name = "reovim-tui-mod-fold"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Fold rendering module for Reovim TUI"
repository.workspace = true

[lints]
workspace = true

[dependencies]
reovim-client-driver = { workspace = true }
reovim-arch = { workspace = true }
serde_json = { workspace = true }
