[package]
name = "reovim-codec-tui-input"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "TUI platform input codec for reovim (keyboard, mouse, scroll)"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
# Enable for building as standalone dynamic library.
dynamic = []

[dependencies]
reovim-input-codec = { workspace = true }
reovim-module-macros = { workspace = true }
reovim-kernel = { workspace = true }
reovim-subsys-input = { workspace = true }
bitflags = "2.4"

[dev-dependencies]
