[package]
name = "reovim-plugin-statusline"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Statusline extension plugin for reovim"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
reovim-core.workspace = true
reovim-plugin-context = { path = "../context" }
tracing.workspace = true

[dev-dependencies]
