[package]
name = "reovim-tui-mod-line-numbers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Line numbers annotation module for Reovim TUI"
repository.workspace = true

[lints]
workspace = true

[dependencies]
reovim-client-driver = { workspace = true }
reovim-arch = { workspace = true }
