[package]
name = "reovim-plugin-explorer"
version.workspace = true
edition.workspace = true
description = "File explorer plugin for reovim"
license.workspace = true
repository.workspace = true

[dependencies]
reovim-core.workspace = true
reovim-sys.workspace = true
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
