coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0.5%
    patch:
      default:
        target: 100%

ignore:
  - "tools/**"
  - "archive/**"
  - "uapi/protocol/src/gen/**"
  - "**/build.rs"
  - "tools/testing/**"
  - "server/lib/drivers/ffi-python/**"
  - "clients/web/**"

comment:
  layout: "header, diff, flags, files"
  require_changes: true

flags:
  branch:
    carryforward: true
  mcdc:
    carryforward: true
