[package]
name = "reovim-module-options"
version = "0.9.0-dev"
edition.workspace = true
license.workspace = true
description = "Editor options and settings module for reovim"
readme = "README.md"
repository.workspace = true

[dependencies]
reovim-kernel = { workspace = true }

[lints]
workspace = true
