[package]
name = "reovim-plugin-lsp"
version.workspace = true
edition.workspace = true
description = "LSP integration plugin for reovim"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reovim-core.workspace = true
reovim-lsp.workspace = true
reovim-plugin-microscope.workspace = true
arc-swap = "1.8"
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
