[package]
name = "reovim-plugin-lsp"
version.workspace = true
edition.workspace = true
description = "LSP integration plugin for reovim"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reovim-core = { path = "../../../lib/core" }
reovim-lsp = { path = "../../../lib/lsp" }
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
