[package]
name = "reovim-driver-input"
version = "0.9.2-dev"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Input driver for reovim (keyboard, mouse, clipboard)"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
reovim-kernel = { path = "../../kernel", version = "0.9.2-dev" }
reovim-arch = { path = "../../arch", version = "0.9.2-dev" }
reovim-driver-session = { path = "../session", version = "0.9.2-dev" }
reovim-driver-command-types = { path = "../command-types", version = "0.9.2-dev" }
bitflags = "2.4"
tracing = "0.1"
