[package]
name = "reovim-tui-ext-defaults"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Default TUI modules meta-crate for reovim"
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Native ClientModule implementations
reovim-client-driver = { workspace = true }
reovim-tui-mod-statusline = { workspace = true }
reovim-tui-mod-hover = { workspace = true }
reovim-tui-mod-signature-help = { workspace = true }
reovim-tui-mod-landing = { workspace = true }
reovim-tui-mod-completion = { workspace = true }
reovim-tui-mod-notification = { workspace = true }
reovim-tui-mod-whichkey = { workspace = true }
reovim-tui-mod-cmdline = { workspace = true }
reovim-tui-mod-microscope = { workspace = true }
reovim-tui-mod-explorer = { workspace = true }
reovim-tui-mod-tetromino = { workspace = true }
reovim-tui-mod-line-numbers = { workspace = true }
reovim-tui-mod-fold = { workspace = true }
reovim-tui-mod-jump = { workspace = true }
reovim-tui-mod-pair = { workspace = true }
reovim-tui-mod-diagnostics = { workspace = true }
reovim-tui-mod-markdown = { workspace = true }
