[package]
name = "reovim-tui-ext-defaults"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Default TUI extensions meta-crate for reovim"
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# Extension trait
reovim-driver-display = { workspace = true }

# Concrete extensions
reovim-tui-ext-whichkey = { path = "../which-key" }
reovim-tui-ext-cmdline = { path = "../cmdline" }
reovim-tui-ext-notification = { path = "../notification" }
reovim-tui-ext-microscope = { path = "../microscope" }
reovim-tui-ext-completion = { path = "../completion" }
reovim-tui-ext-explorer = { path = "../explorer" }
reovim-tui-ext-tetromino = { path = "../tetromino" }
reovim-tui-ext-range-finder = { path = "../range-finder" }
