[package]
name = "reovim-module-git-signs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Git gutter signs module for reovim"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["vim-keybindings"]
vim-keybindings = ["dep:reovim-module-vim"]
dynamic = []

[dependencies]
reovim-module-vim = { workspace = true, optional = true }
reovim-kernel = { workspace = true }
reovim-subsys-git = { workspace = true }
reovim-subsys-annotation = { workspace = true }
reovim-driver-command = { workspace = true }
reovim-subsys-command-types = { workspace = true }
reovim-driver-text-session = { workspace = true }
reovim-driver-text-input = { workspace = true }
reovim-module-macros = { workspace = true }
tracing.workspace = true

[lints]
workspace = true
