[package]
name = "reovim-driver-net-grpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "gRPC server-driver implementation for reovim (tonic + tokio)"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = []
grpc-web = ["dep:tonic-web", "dep:tower-http"]

[dependencies]
reovim-subsys-net = { workspace = true }
reovim-driver-macros = { workspace = true }

tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tower = { version = "0.5.3", features = ["util"] }
http = "1.4.0"
libc = { workspace = true }
async-trait = { workspace = true }

tonic-web = { version = "0.12", optional = true }
tower-http = { version = "0.5", features = ["cors"], optional = true }
