[package]
name = "reovim-plugin-pickers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reovim-core = { path = "../../../lib/core" }
reovim-plugin-microscope = { path = "../microscope" }
tokio = { version = "1", features = ["fs", "process", "io-util"] }
ignore = "0.4"
