[package]
name = "reovim-picker-git-stash"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Git stash picker module for reovim"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
dynamic = []

[dependencies]
reovim-kernel = { workspace = true }
reovim-driver-picker = { workspace = true }
reovim-driver-git = { workspace = true }
reovim-module-macros = { workspace = true }

[lints]
workspace = true
