//! Client module handle — unifies static `Box<dyn ClientModule>` and dynamic
//! `*mut c_void` behind a single lifecycle interface.
//!
// FFI handles inherently require unsafe for raw pointer management,
// Send/Sync impls, and calling extern "C" functions.
#![allow(unsafe_code)]
//!
//! Static modules dispatch directly through the `ClientModule` trait.
//! Dynamic modules dispatch through FFI trampolines generated by
//! `declare_client_module!`.
//!
//! Dynamic modules participate in lifecycle (init/exit/`on_all_loaded`) but
//! rendering methods (chrome, virtual lines, etc.) are not wired through FFI
//! in this phase — they return defaults.

use std::{ffi::c_void, path::PathBuf};

use crate::{
    ClientModule, ClientModuleError, ClientModuleProbe, ModuleContext, ProbeResult, Version,
};

// =============================================================================
// FFI Function Types
// =============================================================================

/// FFI function: probe metadata without instantiation.
pub type ClientProbeFn = unsafe extern "C" fn() -> ClientModuleProbe;

/// FFI function: create module instance.
pub type ClientEntryFn = unsafe extern "C" fn() -> *mut c_void;

/// FFI function: init trampoline.
pub type ClientInitFn = unsafe extern "C" fn(*mut c_void, *const c_void) -> i32;

/// FFI function: exit trampoline.
pub type ClientExitFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: destroy trampoline.
pub type ClientDestroyFn = unsafe extern "C" fn(*mut c_void);

/// FFI function: `on_all_loaded` trampoline.
pub type ClientOnAllLoadedFn = unsafe extern "C" fn(*mut c_void, *const c_void);

// =============================================================================
// ClientFfiSymbols
// =============================================================================

/// Resolved FFI symbols from a dynamic client module shared library.
pub struct ClientFfiSymbols {
    /// Init trampoline.
    pub init: ClientInitFn,
    /// Exit trampoline.
    pub exit: ClientExitFn,
    /// Destroy trampoline.
    pub destroy: ClientDestroyFn,
    /// On-all-loaded trampoline (optional).
    pub on_all_loaded: Option<ClientOnAllLoadedFn>,
}

// =============================================================================
// ClientModuleHandle
// =============================================================================

/// Unified handle for static and dynamic client modules.
///
/// Provides lifecycle dispatch (init/exit/`on_all_loaded`) for both module types.
/// Static modules delegate through `ClientModule` trait. Dynamic modules
/// dispatch through FFI trampolines.
pub struct ClientModuleHandle {
    /// Leaked kind string (for `&'static str` lifetime requirement).
    kind: &'static str,
    /// Module name.
    name: String,
    /// Module version.
    version: Version,
    /// Dependencies (from probe or static module).
    deps: Vec<String>,
    /// Optional dependencies.
    optional_deps: Vec<String>,
    /// Probe metadata (dynamic modules only; kept for introspection).
    #[allow(dead_code)]
    probe: Option<ClientModuleProbe>,
    /// Static module instance.
    static_module: Option<Box<dyn ClientModule>>,
    /// Dynamic module instance pointer.
    dynamic_ptr: Option<*mut c_void>,
    /// Loaded dynamic library (kept alive for FFI symbol lifetime).
    #[allow(dead_code)]
    library: Option<libloading::Library>,
    /// Path to the `.so` file (dynamic modules).
    path: Option<PathBuf>,
    /// FFI symbols (dynamic modules).
    ffi: Option<ClientFfiSymbols>,
}

// SAFETY: ClientModuleHandle is Send+Sync because:
// - Static modules are Box<dyn ClientModule> which requires Send+Sync
// - Dynamic module pointers are only accessed through FFI calls that
//   are inherently single-threaded (called sequentially by the loader)
// - The Library handle is Send+Sync (libloading guarantees)
unsafe impl Send for ClientModuleHandle {}
unsafe impl Sync for ClientModuleHandle {}

impl ClientModuleHandle {
    /// Create a handle wrapping a static `Box<dyn ClientModule>`.
    #[must_use]
    pub fn from_static(module: Box<dyn ClientModule>) -> Self {
        // Leak the kind string so we can return &'static str
        let kind: &'static str = Box::leak(module.kind().to_string().into_boxed_str());
        let name = module.name().to_string();
        let version = module.version();
        let deps = module.dependencies().iter().map(|s| (*s).to_string()).collect();
        let optional_deps = module
            .optional_dependencies()
            .iter()
            .map(|s| (*s).to_string())
            .collect();

        Self {
            kind,
            name,
            version,
            deps,
            optional_deps,
            probe: None,
            static_module: Some(module),
            dynamic_ptr: None,
            library: None,
            path: None,
            ffi: None,
        }
    }

    /// Create a handle wrapping a dynamic module loaded from a `.so`.
    ///
    /// # Safety
    ///
    /// - `ptr` must be a valid pointer from `reovim_client_module_entry()`
    /// - `library` must remain loaded for the lifetime of this handle
    /// - `ffi` symbols must be from the same library
    #[must_use]
    pub unsafe fn from_dynamic(
        library: libloading::Library,
        path: PathBuf,
        probe: ClientModuleProbe,
        ptr: *mut c_void,
        ffi: ClientFfiSymbols,
    ) -> Self {
        let kind: &'static str = Box::leak(probe.id_str().to_string().into_boxed_str());
        let name = probe.name_str().to_string();
        let version = probe.version;
        let deps = probe.required_deps().iter().map(|s| (*s).to_string()).collect();
        let optional_deps = probe.optional_deps().iter().map(|s| (*s).to_string()).collect();

        Self {
            kind,
            name,
            version,
            deps,
            optional_deps,
            probe: Some(probe),
            static_module: None,
            dynamic_ptr: Some(ptr),
            library: Some(library),
            path: Some(path),
            ffi: Some(ffi),
        }
    }

    /// Module kind identifier.
    #[must_use]
    pub const fn kind(&self) -> &'static str {
        self.kind
    }

    /// Human-readable module name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Module version.
    #[must_use]
    pub const fn version(&self) -> Version {
        self.version
    }

    /// Whether this handle wraps a static module.
    #[must_use]
    pub const fn is_static(&self) -> bool {
        self.static_module.is_some()
    }

    /// Whether this handle wraps a dynamic module.
    #[must_use]
    pub const fn is_dynamic(&self) -> bool {
        self.dynamic_ptr.is_some()
    }

    /// Get the static module reference (if static).
    #[must_use]
    pub fn as_module(&self) -> Option<&dyn ClientModule> {
        self.static_module.as_deref()
    }

    /// Get the static module mutable reference (if static).
    pub fn as_module_mut(&mut self) -> Option<&mut dyn ClientModule> {
        self.static_module.as_deref_mut()
    }

    /// Required dependencies.
    pub fn dependencies(&self) -> Vec<&str> {
        self.deps.iter().map(String::as_str).collect()
    }

    /// Optional dependencies.
    pub fn optional_dependencies(&self) -> Vec<&str> {
        self.optional_deps.iter().map(String::as_str).collect()
    }

    /// Path to the `.so` file (dynamic modules only).
    #[must_use]
    pub const fn path(&self) -> Option<&PathBuf> {
        self.path.as_ref()
    }

    /// Initialize the module.
    pub fn init(&mut self, ctx: &ModuleContext) -> ProbeResult {
        if let Some(module) = &mut self.static_module {
            return module.init(ctx);
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            let ctx_ptr = std::ptr::from_ref(ctx).cast::<c_void>();
            // SAFETY: ptr is from entry(), ctx_ptr points to valid ModuleContext
            let code = unsafe { (ffi.init)(ptr, ctx_ptr) };
            return match code {
                0 => ProbeResult::Success,
                1 => ProbeResult::Defer("dynamic module deferred".to_string()),
                _ => ProbeResult::Failed(ClientModuleError {
                    message: format!("dynamic init returned code {code}"),
                }),
            };
        }

        ProbeResult::Failed(ClientModuleError {
            message: "handle has neither static nor dynamic module".to_string(),
        })
    }

    /// Shut down the module.
    ///
    /// # Errors
    ///
    /// Returns an error if the module's exit fails.
    pub fn exit(&mut self) -> Result<(), ClientModuleError> {
        if let Some(module) = &mut self.static_module {
            return module.exit();
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // SAFETY: ptr is from entry()
            let code = unsafe { (ffi.exit)(ptr) };
            return if code == 0 {
                Ok(())
            } else {
                Err(ClientModuleError {
                    message: format!("dynamic exit returned code {code}"),
                })
            };
        }

        Ok(())
    }

    /// Lifecycle hook after all modules are loaded.
    pub fn on_all_loaded(&mut self, ctx: &ModuleContext) {
        if let Some(module) = &mut self.static_module {
            module.on_all_loaded(ctx);
            return;
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(on_all_loaded) = ffi.on_all_loaded
        {
            let ctx_ptr = std::ptr::from_ref(ctx).cast::<c_void>();
            // SAFETY: ptr is from entry(), ctx_ptr points to valid ModuleContext
            unsafe {
                on_all_loaded(ptr, ctx_ptr);
            }
        }
    }
}

impl Drop for ClientModuleHandle {
    fn drop(&mut self) {
        // For dynamic modules: call destroy before unloading library
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr.take(), &self.ffi) {
            // SAFETY: ptr is from entry(), destroy frees it
            unsafe {
                (ffi.destroy)(ptr);
            }
        }
        // Library is dropped automatically, unloading the .so
    }
}

impl std::fmt::Debug for ClientModuleHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ClientModuleHandle")
            .field("kind", &self.kind)
            .field("name", &self.name)
            .field("version", &self.version)
            .field("is_static", &self.is_static())
            .field("is_dynamic", &self.is_dynamic())
            .field("path", &self.path)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
#[path = "handle_tests.rs"]
mod tests;
