[package]
name = "reovim-lang-bash"
version.workspace = true
edition.workspace = true
description = "Bash language support for reovim"
license.workspace = true
repository.workspace = true

[dependencies]
reovim-core = { path = "../../../lib/core" }
reovim-plugin-treesitter = { path = "../../features/treesitter" }
tree-sitter-bash = "0.23"
