[package]
name = "reovim-lang-bash"
version.workspace = true
edition.workspace = true
description = "Bash language support for reovim"
license.workspace = true
repository.workspace = true

[dependencies]
reovim-core.workspace = true
reovim-plugin-treesitter.workspace = true
tree-sitter-bash = "0.23"
