[package]
name = "reovim-tui-mod-landing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Startup landing screen native ClientModule for reovim"
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
reovim-client-subsys-module = { workspace = true }
reovim-client-subsys-chrome = { workspace = true }
reovim-arch = { workspace = true }

[dev-dependencies]
reovim-client-subsys-module = { workspace = true, features = ["testing"] }
reovim-client-subsys-chrome = { workspace = true }
reovim-ext-client-tui-cap-cell = { workspace = true }
