[package]
name = "reovim-lang-toml"
version.workspace = true
edition.workspace = true
description = "TOML language support for reovim"
license.workspace = true
repository.workspace = true

[dependencies]
reovim-core.workspace = true
reovim-plugin-treesitter.workspace = true
tree-sitter-toml-ng = "0.7"

[dev-dependencies]
reovim-driver-syntax.workspace = true
