//! Product-facing executable source-install syscall vocabulary.
//!
//! This leaf owns source-domain install controls for `/bin` and `/payload`
//! source artifacts. The raw syscall leaf remains only the transport spine,
//! while source inventory remains fd-readable through `/proc/sources` and
//! `/proc/media`.

#![no_std]

use {
    core::mem::size_of,
    reovim_uapi_syscall::{RawSyscall, SyscallArgs, SyscallError, SyscallNr},
};

/// Maximum source artifact name bytes retained in an install report.
pub const SOURCE_REPORT_NAME_BYTES: usize = 32;
/// Maximum source-store path bytes retained in an install report.
pub const SOURCE_REPORT_PATH_BYTES: usize = 64;
/// Maximum source-media storage label bytes retained in an install report.
pub const SOURCE_REPORT_STORAGE_BYTES: usize = 32;

/// Source-install control operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceControlOp(usize);

impl SourceControlOp {
    /// Install a status-only `/bin` source image.
    pub const INSTALL_BIN_STATUS: Self = Self(0);
    /// Install a status-only `/payload` source image.
    pub const INSTALL_PAYLOAD_STATUS: Self = Self(1);
    /// Install a `/bin` source image from checked source media.
    pub const INSTALL_BIN_MEDIA: Self = Self(2);
    /// Install a `/payload` source image from checked source media.
    pub const INSTALL_PAYLOAD_MEDIA: Self = Self(3);

    /// Builds a control op from a raw transport scalar.
    #[must_use]
    pub const fn new(raw: usize) -> Self {
        Self(raw)
    }

    /// Returns the raw transport scalar.
    #[must_use]
    pub const fn raw(self) -> usize {
        self.0
    }
}

/// Source artifact namespace code used by structured install reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceNamespaceCode(usize);

impl SourceNamespaceCode {
    /// No source namespace.
    pub const NONE: Self = Self(0);
    /// `/bin` source artifact.
    pub const BIN: Self = Self(1);
    /// `/payload` source artifact.
    pub const PAYLOAD: Self = Self(2);

    /// Builds a namespace code from a stable scalar.
    #[must_use]
    pub const fn new(raw: usize) -> Self {
        Self(raw)
    }

    /// Returns the stable scalar.
    #[must_use]
    pub const fn raw(self) -> usize {
        self.0
    }
}

/// Source-install status code used by structured install reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceInstallStatusCode(usize);

impl SourceInstallStatusCode {
    /// No status applies to this report.
    pub const NONE: Self = Self(0);
    /// Status-only `/bin` image exits successfully.
    pub const OK: Self = Self(1);
    /// Status-only `/bin` image fails.
    pub const ERROR: Self = Self(2);
    /// Status-only payload image reports ready.
    pub const READY: Self = Self(3);
    /// Status-only payload image reports failed.
    pub const FAILED: Self = Self(4);

    /// Builds a status code from a stable scalar.
    #[must_use]
    pub const fn new(raw: usize) -> Self {
        Self(raw)
    }

    /// Returns the stable scalar.
    #[must_use]
    pub const fn raw(self) -> usize {
        self.0
    }
}

/// Source-install origin code used by structured install reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceInstallOriginCode(usize);

impl SourceInstallOriginCode {
    /// No source-install origin.
    pub const NONE: Self = Self(0);
    /// Source bytes were generated by a status-only install request.
    pub const INSTALLED: Self = Self(1);
    /// Source bytes came from checked source media.
    pub const SOURCE_MEDIA: Self = Self(2);

    /// Builds an origin code from a stable scalar.
    #[must_use]
    pub const fn new(raw: usize) -> Self {
        Self(raw)
    }

    /// Returns the stable scalar.
    #[must_use]
    pub const fn raw(self) -> usize {
        self.0
    }
}

/// Structured result of a source-install control operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct SourceInstallReport {
    namespace: usize,
    status: usize,
    origin: usize,
    bytes_len: usize,
    storage_capacity_bytes: usize,
    artifact_bytes_len: usize,
    checksum: u32,
    name_len: usize,
    name_truncated: u8,
    path_len: usize,
    path_truncated: u8,
    storage_len: usize,
    storage_truncated: u8,
    name: [u8; SOURCE_REPORT_NAME_BYTES],
    path: [u8; SOURCE_REPORT_PATH_BYTES],
    storage: [u8; SOURCE_REPORT_STORAGE_BYTES],
}

impl SourceInstallReport {
    /// Empty report value used before a source-install request is issued.
    #[must_use]
    pub const fn empty() -> Self {
        Self {
            namespace: SourceNamespaceCode::NONE.raw(),
            status: SourceInstallStatusCode::NONE.raw(),
            origin: SourceInstallOriginCode::NONE.raw(),
            bytes_len: 0,
            storage_capacity_bytes: 0,
            artifact_bytes_len: 0,
            checksum: 0,
            name_len: 0,
            name_truncated: 0,
            path_len: 0,
            path_truncated: 0,
            storage_len: 0,
            storage_truncated: 0,
            name: [0; SOURCE_REPORT_NAME_BYTES],
            path: [0; SOURCE_REPORT_PATH_BYTES],
            storage: [0; SOURCE_REPORT_STORAGE_BYTES],
        }
    }

    /// Clears this report to the empty value.
    pub fn clear(&mut self) {
        *self = Self::empty();
    }

    /// Records the source namespace.
    pub fn set_namespace(&mut self, namespace: SourceNamespaceCode) {
        self.namespace = namespace.raw();
    }

    /// Records the install status.
    pub fn set_status(&mut self, status: SourceInstallStatusCode) {
        self.status = status.raw();
    }

    /// Records the install origin.
    pub fn set_origin(&mut self, origin: SourceInstallOriginCode) {
        self.origin = origin.raw();
    }

    /// Records the installed source byte count.
    pub fn set_bytes_len(&mut self, bytes_len: usize) {
        self.bytes_len = bytes_len;
    }

    /// Records the source-media storage capacity.
    pub fn set_storage_capacity_bytes(&mut self, capacity: usize) {
        self.storage_capacity_bytes = capacity;
    }

    /// Records the checked source-media artifact byte count.
    pub fn set_artifact_bytes_len(&mut self, bytes_len: usize) {
        self.artifact_bytes_len = bytes_len;
    }

    /// Records the checked source payload checksum.
    pub fn set_checksum(&mut self, checksum: u32) {
        self.checksum = checksum;
    }

    /// Records the canonical source artifact name.
    pub fn set_name(&mut self, name: &str) {
        let (len, truncated) = copy_truncated(name.as_bytes(), &mut self.name);
        self.name_len = len;
        self.name_truncated = u8::from(truncated);
    }

    /// Records the source-store path.
    pub fn set_path(&mut self, path: &str) {
        let (len, truncated) = copy_truncated(path.as_bytes(), &mut self.path);
        self.path_len = len;
        self.path_truncated = u8::from(truncated);
    }

    /// Records the source-media storage label.
    pub fn set_storage(&mut self, storage: &str) {
        let (len, truncated) = copy_truncated(storage.as_bytes(), &mut self.storage);
        self.storage_len = len;
        self.storage_truncated = u8::from(truncated);
    }

    /// Returns the source namespace.
    #[must_use]
    pub const fn namespace(self) -> SourceNamespaceCode {
        SourceNamespaceCode::new(self.namespace)
    }

    /// Returns the install status.
    #[must_use]
    pub const fn status(self) -> SourceInstallStatusCode {
        SourceInstallStatusCode::new(self.status)
    }

    /// Returns the install origin.
    #[must_use]
    pub const fn origin(self) -> SourceInstallOriginCode {
        SourceInstallOriginCode::new(self.origin)
    }

    /// Returns the installed source byte count.
    #[must_use]
    pub const fn bytes_len(self) -> usize {
        self.bytes_len
    }

    /// Returns the source-media storage capacity.
    #[must_use]
    pub const fn storage_capacity_bytes(self) -> usize {
        self.storage_capacity_bytes
    }

    /// Returns the checked source-media artifact byte count.
    #[must_use]
    pub const fn artifact_bytes_len(self) -> usize {
        self.artifact_bytes_len
    }

    /// Returns the checked source payload checksum.
    #[must_use]
    pub const fn checksum(self) -> u32 {
        self.checksum
    }

    /// Returns the canonical source artifact name bytes.
    #[must_use]
    pub fn name_bytes(&self) -> &[u8] {
        &self.name[..self.name_len]
    }

    /// Returns whether the source artifact name was truncated.
    #[must_use]
    pub const fn name_truncated(self) -> bool {
        self.name_truncated != 0
    }

    /// Returns the source-store path bytes.
    #[must_use]
    pub fn path_bytes(&self) -> &[u8] {
        &self.path[..self.path_len]
    }

    /// Returns whether the source-store path was truncated.
    #[must_use]
    pub const fn path_truncated(self) -> bool {
        self.path_truncated != 0
    }

    /// Returns the source-media storage label bytes.
    #[must_use]
    pub fn storage_bytes(&self) -> &[u8] {
        &self.storage[..self.storage_len]
    }

    /// Returns whether the source-media storage label was truncated.
    #[must_use]
    pub const fn storage_truncated(self) -> bool {
        self.storage_truncated != 0
    }
}

/// Product-facing source syscall error.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceError(i32);

impl SourceError {
    /// The requested arguments are not valid for this operation.
    pub const INVALID_ARGUMENT: Self = Self(SyscallError::INVALID_ARGUMENT.code());
    /// This kernel build does not support the requested operation.
    pub const UNSUPPORTED: Self = Self(SyscallError::UNSUPPORTED.code());
    /// No matching source-backed `/bin` or `/payload` descriptor exists.
    pub const NOT_FOUND: Self = Self(SyscallError::NOT_FOUND.code());
    /// The syscall requires an attached current process context.
    pub const NO_CURRENT_PROCESS: Self = Self(SyscallError::NO_CURRENT_PROCESS.code());
    /// The source-media or source-store operation failed.
    pub const IO: Self = Self(SyscallError::IO.code());
    /// The source artifact exceeded the bounded runtime overlay.
    pub const FILE_TOO_LARGE: Self = Self(SyscallError::FILE_TOO_LARGE.code());
    /// No runtime source overlay slot was available.
    pub const BUSY: Self = Self(SyscallError::BUSY.code());
    /// The requested source image failed validation.
    pub const INVALID_IMAGE: Self = Self(SyscallError::INVALID_IMAGE.code());
    /// No source-media target is installed.
    pub const SOURCE_MEDIA_UNAVAILABLE: Self = Self(SyscallError::SOURCE_MEDIA_UNAVAILABLE.code());
    /// The source-media target failed to read a bounded artifact.
    pub const SOURCE_MEDIA_READ_FAILED: Self = Self(SyscallError::SOURCE_MEDIA_READ_FAILED.code());
    /// Source-media artifact namespace does not match the requested install kind.
    pub const SOURCE_MEDIA_NAMESPACE_MISMATCH: Self =
        Self(SyscallError::SOURCE_MEDIA_NAMESPACE_MISMATCH.code());
    /// Source-media artifact path does not match the requested descriptor.
    pub const SOURCE_MEDIA_PATH_MISMATCH: Self =
        Self(SyscallError::SOURCE_MEDIA_PATH_MISMATCH.code());

    /// Builds a source error from a transport code.
    #[must_use]
    pub const fn new(code: i32) -> Self {
        Self(code)
    }

    /// Returns the stable transport code.
    #[must_use]
    pub const fn code(self) -> i32 {
        self.0
    }
}

/// Source-install control backed by the raw Reovim syscall transport.
#[derive(Debug, Clone, Copy)]
pub struct SyscallSourceControl {
    raw: RawSyscall,
}

impl SyscallSourceControl {
    /// Creates a source control adapter over the raw syscall transport.
    #[must_use]
    pub const fn new(raw: RawSyscall) -> Self {
        Self { raw }
    }

    /// Installs a status-only `/bin` source image.
    ///
    /// # Errors
    ///
    /// Returns [`SourceError`] when `name` is empty, the status is not
    /// [`SourceInstallStatusCode::OK`] or [`SourceInstallStatusCode::ERROR`],
    /// or the kernel rejects the install request.
    pub fn install_bin_status(
        self,
        name: &str,
        status: SourceInstallStatusCode,
    ) -> Result<SourceInstallReport, SourceError> {
        if status != SourceInstallStatusCode::OK && status != SourceInstallStatusCode::ERROR {
            return Err(SourceError::INVALID_ARGUMENT);
        }
        self.install_report(SourceControlOp::INSTALL_BIN_STATUS, name, status)
    }

    /// Installs a status-only `/payload` source image.
    ///
    /// # Errors
    ///
    /// Returns [`SourceError`] when `name` is empty, the status is not
    /// [`SourceInstallStatusCode::READY`] or [`SourceInstallStatusCode::FAILED`],
    /// or the kernel rejects the install request.
    pub fn install_payload_status(
        self,
        name: &str,
        status: SourceInstallStatusCode,
    ) -> Result<SourceInstallReport, SourceError> {
        if status != SourceInstallStatusCode::READY && status != SourceInstallStatusCode::FAILED {
            return Err(SourceError::INVALID_ARGUMENT);
        }
        self.install_report(SourceControlOp::INSTALL_PAYLOAD_STATUS, name, status)
    }

    /// Installs a `/bin` source image from checked source media.
    ///
    /// # Errors
    ///
    /// Returns [`SourceError`] when `name` is empty or the kernel rejects the
    /// source-media install request.
    pub fn install_bin_media(self, name: &str) -> Result<SourceInstallReport, SourceError> {
        self.install_report(SourceControlOp::INSTALL_BIN_MEDIA, name, SourceInstallStatusCode::NONE)
    }

    /// Installs a `/payload` source image from checked source media.
    ///
    /// # Errors
    ///
    /// Returns [`SourceError`] when `name` is empty or the kernel rejects the
    /// source-media install request.
    pub fn install_payload_media(self, name: &str) -> Result<SourceInstallReport, SourceError> {
        self.install_report(
            SourceControlOp::INSTALL_PAYLOAD_MEDIA,
            name,
            SourceInstallStatusCode::NONE,
        )
    }

    fn install_report(
        self,
        op: SourceControlOp,
        name: &str,
        status: SourceInstallStatusCode,
    ) -> Result<SourceInstallReport, SourceError> {
        if name.is_empty() {
            return Err(SourceError::INVALID_ARGUMENT);
        }
        let mut report = SourceInstallReport::empty();
        self.raw
            .invoke(
                SyscallNr::SOURCE_CONTROL,
                SyscallArgs::new([
                    op.raw(),
                    name.as_ptr().addr(),
                    name.len(),
                    status.raw(),
                    (&raw mut report).addr(),
                    size_of::<SourceInstallReport>(),
                ]),
            )
            .decode()
            .map(|_| report)
            .map_err(source_error_from_syscall)
    }
}

fn copy_truncated(src: &[u8], dst: &mut [u8]) -> (usize, bool) {
    dst.fill(0);
    let len = src.len().min(dst.len());
    dst[..len].copy_from_slice(&src[..len]);
    (len, len < src.len())
}

fn source_error_from_syscall(error: SyscallError) -> SourceError {
    SourceError::new(error.code())
}
