//! Client module handle — unifies static `Box<dyn ClientModule>` and dynamic
//! `*mut c_void` behind a single lifecycle interface.
//!
// FFI handles inherently require unsafe for raw pointer management,
// Send/Sync impls, and calling extern "C" functions.
#![allow(unsafe_code)]
//!
//! Static modules dispatch directly through the `ClientModule` trait.
//! Dynamic modules dispatch through FFI trampolines generated by
//! `declare_client_module!`.
//!
//! Dynamic modules now participate in lifecycle, events, chrome metadata, and
//! the #723 render/event FFI surface. The only remaining dynamic limitation is
//! the borrowed-slice trait hooks in the TUI wrapper (`fold_ranges`,
//! `virtual_lines`, `inline_decorations`), which cannot be exposed soundly
//! until the trait returns owned data.

use std::{
    ffi::c_void,
    path::{Path, PathBuf},
};

use crate::{
    AnnotationContext, BufferId, BufferUpdateEvent, ChromePosition, ClientModule,
    ClientModuleError, ClientModuleProbe, ColumnWidth, GutterCell, InlineDecoration, ModuleContext,
    OptionValue, ProbeResult, Rect, RenderBehavior, ChromeSurface, TransformedLine, Version,
    VirtualLine,
    ffi::{
        FfiAnnotationContext, FfiColumnWidth, FfiFoldRange, FfiGutterCell, FfiInlineDecoration,
        FfiPlatformCaps, FfiRenderBehavior, FfiRenderSurface, FfiRenderSurfaceHost,
        FfiThemeProvider, FfiThemeProviderHost, FfiTransformedLine, FfiVirtualLine,
    },
    traits::{PlatformCapabilities, ThemeProvider},
    types::{CLIENT_MODULE_API_VERSION, is_client_compatible},
};

// =============================================================================
// Leak counters and constants
// =============================================================================

/// Fixed static allocations leaked per [`ClientModuleHandle`] construction.
///
/// Counts the 4 fixed leaks: `kind`, `name`, `deps` slice, `optional_deps` slice.
/// Does NOT include individual dependency strings (which vary per module).
///
/// Use [`expected_handle_leaks`] (test-only) to compute the total expected leaks
/// for a handle with a given dep count.
///
/// Bounded by module count (max ~20 client modules), ~200 bytes total per handle.
/// See the #724 countdown addendum for rationale.
pub const HANDLE_LEAKS_PER_MODULE_FIXED: usize = 4;

/// Compute the total expected `Box::leak` count for a handle whose module
/// declares `required_deps` required dependencies and `optional_deps` optional.
///
/// Test-only helper used by the leak-bound test (T2) in `handle_tests.rs`.
#[cfg(test)]
#[allow(dead_code)] // consumed by T2 leak bound test
pub(crate) const fn expected_handle_leaks(required_deps: usize, optional_deps: usize) -> usize {
    HANDLE_LEAKS_PER_MODULE_FIXED + required_deps + optional_deps
}

/// Test-only counter for [`Box::leak`] calls inside [`ClientModuleHandle`]
/// construction. Used by the T2 leak-bound test to verify that each handle
/// produces a predictable number of leaked allocations.
#[cfg(test)]
pub(crate) static HANDLE_LEAK_COUNTER: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(0);

/// Leak a `String` into `&'static str`, incrementing the test counter.
fn leak_str(s: String) -> &'static str {
    #[cfg(test)]
    HANDLE_LEAK_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    Box::leak(s.into_boxed_str())
}

/// Leak a vector of strings into `&'static [&'static str]`, incrementing the
/// test counter once for each element string PLUS once for the slice itself.
fn leak_str_slice(strs: Vec<String>) -> &'static [&'static str] {
    let leaked: Vec<&'static str> = strs.into_iter().map(leak_str).collect();
    #[cfg(test)]
    HANDLE_LEAK_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    Box::leak(leaked.into_boxed_slice())
}

/// Direct test access to the leak wrappers so T2 can exercise the counter
/// outside of full handle construction.
#[cfg(test)]
#[allow(dead_code)] // consumed by handle_tests::leak_wrapper_*
pub(crate) fn test_leak_str(s: String) -> &'static str {
    leak_str(s)
}

/// Direct test access to the slice-leak wrapper.
#[cfg(test)]
#[allow(dead_code)] // consumed by handle_tests::leak_wrapper_*
pub(crate) fn test_leak_str_slice(strs: Vec<String>) -> &'static [&'static str] {
    leak_str_slice(strs)
}

// =============================================================================
// LoadError — failures from `ClientModuleHandle::load_from_path`
// =============================================================================

/// Error returned from [`ClientModuleHandle::load_from_path`] when a dynamic
/// client module `.so` cannot be loaded.
///
/// Error messages are part of the test contract (T5) — downstream diagnostics
/// and the discovery filter code rely on them to log skip reasons. Do NOT
/// rename these variants or change the `Display` output without updating the
/// tests in `handle_tests.rs`.
#[derive(Debug)]
pub enum LoadError {
    /// The path does not exist on disk.
    FileNotFound(PathBuf),
    /// `libloading::Library::new` failed (not a shared library, dlopen error).
    DlopenFailed(String),
    /// The `REOVIM_CLIENT_MODULE_API_VERSION` symbol was not found.
    MissingApiVersion(String),
    /// The module's API version is not compatible with the host.
    IncompatibleApiVersion {
        /// Version advertised by the module's `.so`.
        module: (u32, u32),
        /// Version provided by this host.
        host: (u32, u32),
    },
    /// A required FFI symbol is missing from the `.so`.
    MissingSymbol {
        /// Name of the missing symbol (e.g., `reovim_client_module_probe`).
        symbol: String,
        /// Underlying `libloading` error message.
        source: String,
    },
    /// `reovim_client_module_entry()` returned a null pointer.
    EntryReturnedNull,
}

impl std::fmt::Display for LoadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FileNotFound(path) => {
                write!(f, "dlopen failed: file not found: {}", path.display())
            }
            Self::DlopenFailed(msg) => write!(f, "dlopen failed: {msg}"),
            Self::MissingApiVersion(msg) => write!(f, "no API version symbol: {msg}"),
            Self::IncompatibleApiVersion { module, host } => write!(
                f,
                "incompatible API version: module requires {}.{}, host provides {}.{}",
                module.0, module.1, host.0, host.1,
            ),
            Self::MissingSymbol { symbol, source } => write!(f, "no {symbol} symbol: {source}"),
            Self::EntryReturnedNull => write!(f, "entry returned null"),
        }
    }
}

impl std::error::Error for LoadError {}

// =============================================================================
// FFI Function Types
// =============================================================================

/// FFI function: probe metadata without instantiation.
pub type ClientProbeFn = unsafe extern "C" fn() -> ClientModuleProbe;

/// FFI function: create module instance.
pub type ClientEntryFn = unsafe extern "C" fn() -> *mut c_void;

/// FFI function: init trampoline.
pub type ClientInitFn = unsafe extern "C" fn(*mut c_void, *const c_void) -> i32;

/// FFI function: exit trampoline.
pub type ClientExitFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: destroy trampoline.
pub type ClientDestroyFn = unsafe extern "C" fn(*mut c_void);

/// FFI function: `on_all_loaded` trampoline.
pub type ClientOnAllLoadedFn = unsafe extern "C" fn(*mut c_void, *const c_void);

// -- Event FFI function types ------------------------------------------------

/// FFI function: `on_notification` trampoline (data ptr + len).
pub type ClientOnNotificationFn = unsafe extern "C" fn(*mut c_void, *const u8, usize);

/// FFI function: `on_mode_change` trampoline (mode ptr + len).
pub type ClientOnModeChangeFn = unsafe extern "C" fn(*mut c_void, *const u8, usize);

/// FFI function: `on_cursor_update` trampoline (`buffer_id`, line, col).
pub type ClientOnCursorUpdateFn = unsafe extern "C" fn(*mut c_void, usize, usize, usize);

/// FFI function: `on_buffer_focus` trampoline (`buffer_id`).
pub type ClientOnBufferFocusFn = unsafe extern "C" fn(*mut c_void, usize);

/// FFI function: `on_buffer_update` trampoline
/// (`buffer_id`, revision, `changed_start`, `changed_end`, `total_lines`).
pub type ClientOnBufferUpdateFn =
    unsafe extern "C" fn(*mut c_void, usize, u64, usize, usize, usize);

/// FFI function: `on_option_changed` trampoline
/// (`name_ptr`, `name_len`, tag, `i64_val`, `str_ptr`, `str_len`).
/// Tag encoding: 0 = Bool (i64 != 0), 1 = Integer (i64), 2 = String (`str_ptr` + `str_len`).
pub type ClientOnOptionChangedFn =
    unsafe extern "C" fn(*mut c_void, *const u8, usize, i32, i64, *const u8, usize);

/// FFI function: `tick` trampoline. Returns 1 if redraw needed, 0 otherwise.
pub type ClientTickFn = unsafe extern "C" fn(*mut c_void) -> i32;

// -- Role declaration FFI function types -------------------------------------

/// FFI function: `has_chrome` trampoline. Returns 1 if true, 0 if false.
pub type ClientHasChromeFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: `has_buffer_contrib` trampoline. Returns 1 if true, 0 if false.
pub type ClientHasBufferContribFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: `has_annotations` trampoline. Returns 1 if true, 0 if false.
pub type ClientHasAnnotationsFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: `chrome_position` trampoline.
/// Returns encoded integer: 0=Top, 1=Bottom, 2=Left, 3=Right, 4=Overlay.
pub type ClientChromePositionFn = unsafe extern "C" fn(*mut c_void) -> i32;

/// FFI function: `chrome_requested_size` trampoline.
pub type ClientChromeRequestedSizeFn =
    unsafe extern "C" fn(*mut c_void, *const FfiPlatformCaps) -> u16;

/// FFI function: `chrome_priority` trampoline.
pub type ClientChromePriorityFn = unsafe extern "C" fn(*mut c_void) -> u16;

/// FFI function: `chrome_z_order` trampoline.
pub type ClientChromeZOrderFn = unsafe extern "C" fn(*mut c_void) -> u16;

/// FFI function: `buffer_contrib_priority` trampoline.
pub type ClientBufferContribPriorityFn = unsafe extern "C" fn(*mut c_void) -> u16;

/// FFI function: `annotation_priority` trampoline.
pub type ClientAnnotationPriorityFn = unsafe extern "C" fn(*mut c_void) -> u16;

// -- Render FFI function types (#723, API 0.4.0) -----------------------------

/// FFI function: `chrome_render` trampoline.
pub type ClientChromeRenderFn =
    unsafe extern "C" fn(*mut c_void, *mut FfiRenderSurface, Rect, *const FfiPlatformCaps);

/// FFI function: `annotate` trampoline.
pub type ClientAnnotateFn =
    unsafe extern "C" fn(*mut c_void, usize, *const FfiAnnotationContext) -> FfiGutterCell;

/// FFI function: `annotation_column_width` trampoline.
pub type ClientAnnotationColumnWidthFn = unsafe extern "C" fn(
    *mut c_void,
    *const FfiAnnotationContext,
    *const FfiPlatformCaps,
) -> FfiColumnWidth;

/// FFI function: `transform_line` trampoline.
pub type ClientTransformLineFn =
    unsafe extern "C" fn(*mut c_void, usize, usize, *const u8, usize) -> *mut FfiTransformedLine;

/// FFI function: free a transformed line allocated by the same module.
pub type ClientFreeTransformedLineFn = unsafe extern "C" fn(*mut FfiTransformedLine);

/// FFI function: `map_cursor_column` trampoline. Returns -1 for `None`.
pub type ClientMapCursorColumnFn = unsafe extern "C" fn(*mut c_void, usize, usize, usize) -> i32;

/// FFI function: `fold_ranges` trampoline (out-ptr pattern).
pub type ClientFoldRangesFn =
    unsafe extern "C" fn(*mut c_void, *mut *const FfiFoldRange, *mut usize);

/// FFI function: `virtual_lines` trampoline (out-ptr pattern).
pub type ClientVirtualLinesFn =
    unsafe extern "C" fn(*mut c_void, *mut *const FfiVirtualLine, *mut usize);

/// FFI function: `inline_decorations` trampoline (out-ptr pattern).
pub type ClientInlineDecorationsFn =
    unsafe extern "C" fn(*mut c_void, usize, *mut *const FfiInlineDecoration, *mut usize);

/// FFI function: `cursor_position` trampoline.
///
/// Writes `out_col`/`out_row` and returns 1 if a cursor was set, 0 otherwise.
pub type ClientCursorPositionFn =
    unsafe extern "C" fn(*mut c_void, u16, u16, *mut u16, *mut u16) -> i32;

/// FFI function: `classify_token` trampoline.
pub type ClientClassifyTokenFn =
    unsafe extern "C" fn(*mut c_void, *const u8, usize) -> FfiRenderBehavior;

/// FFI function: `on_capabilities_changed` trampoline.
pub type ClientOnCapabilitiesChangedFn = unsafe extern "C" fn(*mut c_void, *const FfiPlatformCaps);

/// FFI function: `on_theme_changed` trampoline.
pub type ClientOnThemeChangedFn = unsafe extern "C" fn(*mut c_void, *const FfiThemeProvider);

// =============================================================================
// ClientFfiSymbols
// =============================================================================

/// Resolved FFI symbols from a dynamic client module shared library.
pub struct ClientFfiSymbols {
    // -- Lifecycle -----------------------------------------------------------
    /// Init trampoline.
    pub init: ClientInitFn,
    /// Exit trampoline.
    pub exit: ClientExitFn,
    /// Destroy trampoline.
    pub destroy: ClientDestroyFn,
    /// On-all-loaded trampoline (optional).
    pub on_all_loaded: Option<ClientOnAllLoadedFn>,

    // -- Events (optional — absent in pre-0.3.0 modules) ---------------------
    /// On-notification trampoline.
    pub on_notification: Option<ClientOnNotificationFn>,
    /// On-mode-change trampoline.
    pub on_mode_change: Option<ClientOnModeChangeFn>,
    /// On-cursor-update trampoline.
    pub on_cursor_update: Option<ClientOnCursorUpdateFn>,
    /// On-buffer-focus trampoline.
    pub on_buffer_focus: Option<ClientOnBufferFocusFn>,
    /// On-buffer-update trampoline.
    pub on_buffer_update: Option<ClientOnBufferUpdateFn>,
    /// On-option-changed trampoline.
    pub on_option_changed: Option<ClientOnOptionChangedFn>,
    /// Tick trampoline.
    pub tick: Option<ClientTickFn>,

    // -- Role declaration (optional — absent in pre-0.3.0 modules) -----------
    /// Has-chrome trampoline.
    pub has_chrome: Option<ClientHasChromeFn>,
    /// Has-buffer-contrib trampoline.
    pub has_buffer_contrib: Option<ClientHasBufferContribFn>,
    /// Has-annotations trampoline.
    pub has_annotations: Option<ClientHasAnnotationsFn>,
    /// Chrome-position trampoline.
    pub chrome_position: Option<ClientChromePositionFn>,
    /// Chrome-requested-size trampoline.
    pub chrome_requested_size: Option<ClientChromeRequestedSizeFn>,
    /// Chrome-priority trampoline.
    pub chrome_priority: Option<ClientChromePriorityFn>,
    /// Chrome-z-order trampoline.
    pub chrome_z_order: Option<ClientChromeZOrderFn>,
    /// Buffer-contrib-priority trampoline.
    pub buffer_contrib_priority: Option<ClientBufferContribPriorityFn>,
    /// Annotation-priority trampoline.
    pub annotation_priority: Option<ClientAnnotationPriorityFn>,

    // -- Render (#723 — optional, absent in pre-0.4.0 modules) ---------------
    /// Chrome-render trampoline.
    pub chrome_render: Option<ClientChromeRenderFn>,
    /// Annotate trampoline.
    pub annotate: Option<ClientAnnotateFn>,
    /// Annotation-column-width trampoline.
    pub annotation_column_width: Option<ClientAnnotationColumnWidthFn>,
    /// Transform-line trampoline.
    pub transform_line: Option<ClientTransformLineFn>,
    /// Free-transformed-line trampoline (module-side deallocator).
    pub free_transformed_line: Option<ClientFreeTransformedLineFn>,
    /// Map-cursor-column trampoline.
    pub map_cursor_column: Option<ClientMapCursorColumnFn>,
    /// Fold-ranges trampoline.
    pub fold_ranges: Option<ClientFoldRangesFn>,
    /// Virtual-lines trampoline.
    pub virtual_lines: Option<ClientVirtualLinesFn>,
    /// Inline-decorations trampoline.
    pub inline_decorations: Option<ClientInlineDecorationsFn>,
    /// Cursor-position trampoline.
    pub cursor_position: Option<ClientCursorPositionFn>,
    /// Classify-token trampoline.
    pub classify_token: Option<ClientClassifyTokenFn>,

    // -- Events (#723 — optional, absent in pre-0.4.0 modules) ---------------
    /// On-capabilities-changed trampoline.
    pub on_capabilities_changed: Option<ClientOnCapabilitiesChangedFn>,
    /// On-theme-changed trampoline.
    pub on_theme_changed: Option<ClientOnThemeChangedFn>,
}

// =============================================================================
// ClientModuleHandle
// =============================================================================

/// Unified handle for static and dynamic client modules.
///
/// Provides lifecycle dispatch (init/exit/`on_all_loaded`) for both module types.
/// Static modules delegate through `ClientModule` trait. Dynamic modules
/// dispatch through FFI trampolines.
///
/// # Leaked identity strings
///
/// `kind`, `name`, `deps`, and `optional_deps` are stored as `&'static` slices
/// backed by [`Box::leak`]. This is a deliberate bounded leak (max ~20 modules
/// × a handful of short strings each) that exists so [`ClientModule::name`]
/// and friends can return `&'static str` / `&[&'static str]` directly, which
/// in turn lets `DynamicClientModule` (a thin wrapper over this handle)
/// implement the full `ClientModule` trait without its own second-order leaks.
///
/// See [`HANDLE_LEAKS_PER_MODULE_FIXED`] and the #724 countdown addendum.
pub struct ClientModuleHandle {
    /// Leaked kind string (for `&'static str` lifetime requirement).
    kind: &'static str,
    /// Leaked module name.
    name: &'static str,
    /// Module version.
    version: Version,
    /// Required dependencies (leaked slice of leaked strings).
    deps: &'static [&'static str],
    /// Optional dependencies (leaked slice of leaked strings).
    optional_deps: &'static [&'static str],
    /// Probe metadata (dynamic modules only; kept for introspection).
    #[allow(dead_code)]
    probe: Option<ClientModuleProbe>,
    /// Static module instance.
    static_module: Option<Box<dyn ClientModule>>,
    /// Dynamic module instance pointer.
    dynamic_ptr: Option<*mut c_void>,
    /// Loaded dynamic library (kept alive for FFI symbol lifetime).
    #[allow(dead_code)]
    library: Option<libloading::Library>,
    /// Path to the `.so` file (dynamic modules).
    path: Option<PathBuf>,
    /// FFI symbols (dynamic modules).
    ffi: Option<ClientFfiSymbols>,
}

// SAFETY: ClientModuleHandle is Send+Sync because:
// - Static modules are Box<dyn ClientModule> which requires Send+Sync
// - Dynamic module pointers are only accessed through FFI calls that
//   are inherently single-threaded (called sequentially by the loader)
// - The Library handle is Send+Sync (libloading guarantees)
unsafe impl Send for ClientModuleHandle {}
unsafe impl Sync for ClientModuleHandle {}

#[cfg_attr(coverage_nightly, coverage(off))]
impl ClientModuleHandle {
    /// Create a handle wrapping a static `Box<dyn ClientModule>`.
    ///
    /// Leaks the module's identity strings (kind, name, dependencies) per the
    /// bounded-leak rationale on [`ClientModuleHandle`].
    #[must_use]
    pub fn from_static(module: Box<dyn ClientModule>) -> Self {
        let kind = leak_str(module.kind().to_string());
        let name = leak_str(module.name().to_string());
        let version = module.version();
        let deps_vec: Vec<String> = module
            .dependencies()
            .iter()
            .map(|s| (*s).to_string())
            .collect();
        let optional_deps_vec: Vec<String> = module
            .optional_dependencies()
            .iter()
            .map(|s| (*s).to_string())
            .collect();
        let deps = leak_str_slice(deps_vec);
        let optional_deps = leak_str_slice(optional_deps_vec);

        Self {
            kind,
            name,
            version,
            deps,
            optional_deps,
            probe: None,
            static_module: Some(module),
            dynamic_ptr: None,
            library: None,
            path: None,
            ffi: None,
        }
    }

    /// Create a handle wrapping a dynamic module loaded from a `.so`.
    ///
    /// # Safety
    ///
    /// - `ptr` must be a valid pointer from `reovim_client_module_entry()`
    /// - `library` must remain loaded for the lifetime of this handle
    /// - `ffi` symbols must be from the same library
    // Requires a real .so with FFI exports — integration test territory.
    #[cfg_attr(coverage_nightly, coverage(off))]
    #[must_use]
    pub unsafe fn from_dynamic(
        library: libloading::Library,
        path: PathBuf,
        probe: ClientModuleProbe,
        ptr: *mut c_void,
        ffi: ClientFfiSymbols,
    ) -> Self {
        // Leak all identity strings up-front so handle accessors can return
        // `&'static` references that `DynamicClientModule` forwards directly
        // to the `ClientModule` trait (no second-order leak in the wrapper).
        let kind = leak_str(probe.id_str().to_string());
        let name = leak_str(probe.name_str().to_string());
        let version = probe.version;
        let deps_vec: Vec<String> = probe
            .required_deps()
            .iter()
            .map(|s| (*s).to_string())
            .collect();
        let optional_deps_vec: Vec<String> = probe
            .optional_deps()
            .iter()
            .map(|s| (*s).to_string())
            .collect();
        let deps = leak_str_slice(deps_vec);
        let optional_deps = leak_str_slice(optional_deps_vec);

        Self {
            kind,
            name,
            version,
            deps,
            optional_deps,
            probe: Some(probe),
            static_module: None,
            dynamic_ptr: Some(ptr),
            library: Some(library),
            path: Some(path),
            ffi: Some(ffi),
        }
    }

    /// Load a dynamic client module from a `.so` path.
    ///
    /// Performs:
    /// 1. `dlopen` the shared library (fails with [`LoadError::FileNotFound`]
    ///    or [`LoadError::DlopenFailed`]).
    /// 2. Read `REOVIM_CLIENT_MODULE_API_VERSION` and reject incompatible
    ///    modules.
    /// 3. Call `reovim_client_module_probe()` for identity metadata.
    /// 4. Call `reovim_client_module_entry()` for the module instance pointer.
    /// 5. Resolve the 3 required FFI symbols (`init`, `exit`, `destroy`) and
    ///    the 20 optional event/role/chrome/priority symbols.
    /// 6. Build the [`ClientModuleHandle`] via [`Self::from_dynamic`].
    ///
    /// Error messages follow the format asserted by T5 tests in
    /// `handle_tests.rs`.
    ///
    /// # Safety
    ///
    /// The caller must ensure the path points to a shared library built from
    /// workspace source with matching ABI. Loading untrusted `.so` files
    /// executes arbitrary native code.
    ///
    /// # Errors
    ///
    /// Returns [`LoadError`] if the library cannot be opened, the API version
    /// symbol is missing or incompatible, a required FFI symbol is not found,
    /// or `reovim_client_module_entry()` returns null.
    // Full load path requires a real .so with declare_client_module! FFI exports;
    // covered by T1/T5 integration tests against the minimal fixture. Length
    // justification: one `library.get` per FFI symbol (3 required + 17 optional),
    // each with its own error mapping — splitting into helpers would obscure the
    // 1:1 correspondence to the FFI contract.
    #[cfg_attr(coverage_nightly, coverage(off))]
    #[allow(clippy::too_many_lines)]
    pub unsafe fn load_from_path(path: &Path) -> Result<Self, LoadError> {
        use libloading::{Library, Symbol};

        // 1. Check file existence so we return a distinct error variant from
        //    "dlopen failed on a file that does exist."
        if !path.exists() {
            return Err(LoadError::FileNotFound(path.to_path_buf()));
        }

        // SAFETY: The entire function body is `unsafe` because every FFI
        // operation requires the ABI guarantees documented above. The caller
        // has accepted that contract by invoking `load_from_path`.
        unsafe {
            // 2. dlopen
            let library = Library::new(path).map_err(|e| LoadError::DlopenFailed(e.to_string()))?;

            // 3. API version check (fast static symbol).
            let api_version: Symbol<&'static Version> = library
                .get(b"REOVIM_CLIENT_MODULE_API_VERSION")
                .map_err(|e| LoadError::MissingApiVersion(e.to_string()))?;
            let module_api = **api_version;
            if !is_client_compatible(module_api, CLIENT_MODULE_API_VERSION) {
                return Err(LoadError::IncompatibleApiVersion {
                    module: (module_api.major, module_api.minor),
                    host: (CLIENT_MODULE_API_VERSION.major, CLIENT_MODULE_API_VERSION.minor),
                });
            }

            // 4. Probe metadata.
            let probe_fn: Symbol<ClientProbeFn> = library
                .get(b"reovim_client_module_probe")
                .map_err(|e| LoadError::MissingSymbol {
                    symbol: "reovim_client_module_probe".to_string(),
                    source: e.to_string(),
                })?;
            let probe = probe_fn();

            // 5. Entry (instance creation).
            let entry_fn: Symbol<ClientEntryFn> = library
                .get(b"reovim_client_module_entry")
                .map_err(|e| LoadError::MissingSymbol {
                    symbol: "reovim_client_module_entry".to_string(),
                    source: e.to_string(),
                })?;
            let ptr = entry_fn();
            if ptr.is_null() {
                return Err(LoadError::EntryReturnedNull);
            }

            // 6. Required lifecycle symbols.
            let init_sym: Symbol<ClientInitFn> = library
                .get(b"reovim_client_module_init")
                .map_err(|e| LoadError::MissingSymbol {
                    symbol: "reovim_client_module_init".to_string(),
                    source: e.to_string(),
                })?;
            let exit_sym: Symbol<ClientExitFn> = library
                .get(b"reovim_client_module_exit")
                .map_err(|e| LoadError::MissingSymbol {
                    symbol: "reovim_client_module_exit".to_string(),
                    source: e.to_string(),
                })?;
            let destroy_sym: Symbol<ClientDestroyFn> = library
                .get(b"reovim_client_module_destroy")
                .map_err(|e| LoadError::MissingSymbol {
                    symbol: "reovim_client_module_destroy".to_string(),
                    source: e.to_string(),
                })?;

            // 7. Optional symbols (graceful degradation for pre-0.3.0 modules).
            //    Missing symbols become `None` — the handle's dispatch methods
            //    return the documented default behavior.
            let on_all_loaded = library
                .get::<ClientOnAllLoadedFn>(b"reovim_client_module_on_all_loaded")
                .ok()
                .map(|s| *s);
            let on_notification = library
                .get::<ClientOnNotificationFn>(b"reovim_client_module_on_notification")
                .ok()
                .map(|s| *s);
            let on_mode_change = library
                .get::<ClientOnModeChangeFn>(b"reovim_client_module_on_mode_change")
                .ok()
                .map(|s| *s);
            let on_cursor_update = library
                .get::<ClientOnCursorUpdateFn>(b"reovim_client_module_on_cursor_update")
                .ok()
                .map(|s| *s);
            let on_buffer_focus = library
                .get::<ClientOnBufferFocusFn>(b"reovim_client_module_on_buffer_focus")
                .ok()
                .map(|s| *s);
            let on_buffer_update = library
                .get::<ClientOnBufferUpdateFn>(b"reovim_client_module_on_buffer_update")
                .ok()
                .map(|s| *s);
            let on_option_changed = library
                .get::<ClientOnOptionChangedFn>(b"reovim_client_module_on_option_changed")
                .ok()
                .map(|s| *s);
            let tick = library
                .get::<ClientTickFn>(b"reovim_client_module_tick")
                .ok()
                .map(|s| *s);
            let has_chrome = library
                .get::<ClientHasChromeFn>(b"reovim_client_module_has_chrome")
                .ok()
                .map(|s| *s);
            let has_buffer_contrib = library
                .get::<ClientHasBufferContribFn>(b"reovim_client_module_has_buffer_contrib")
                .ok()
                .map(|s| *s);
            let has_annotations = library
                .get::<ClientHasAnnotationsFn>(b"reovim_client_module_has_annotations")
                .ok()
                .map(|s| *s);
            let chrome_position = library
                .get::<ClientChromePositionFn>(b"reovim_client_module_chrome_position")
                .ok()
                .map(|s| *s);
            let chrome_requested_size = library
                .get::<ClientChromeRequestedSizeFn>(b"reovim_client_module_chrome_requested_size")
                .ok()
                .map(|s| *s);
            let chrome_priority = library
                .get::<ClientChromePriorityFn>(b"reovim_client_module_chrome_priority")
                .ok()
                .map(|s| *s);
            let chrome_z_order = library
                .get::<ClientChromeZOrderFn>(b"reovim_client_module_chrome_z_order")
                .ok()
                .map(|s| *s);
            let buffer_contrib_priority = library
                .get::<ClientBufferContribPriorityFn>(
                    b"reovim_client_module_buffer_contrib_priority",
                )
                .ok()
                .map(|s| *s);
            let annotation_priority = library
                .get::<ClientAnnotationPriorityFn>(b"reovim_client_module_annotation_priority")
                .ok()
                .map(|s| *s);

            // #723 render-path optional symbols (API 0.4.0). Absent in 0.3.0
            // modules — the handle's dispatch methods fall through to trait
            // defaults when `None`.
            let chrome_render = library
                .get::<ClientChromeRenderFn>(b"reovim_client_module_chrome_render")
                .ok()
                .map(|s| *s);
            let annotate = library
                .get::<ClientAnnotateFn>(b"reovim_client_module_annotate")
                .ok()
                .map(|s| *s);
            let annotation_column_width = library
                .get::<ClientAnnotationColumnWidthFn>(
                    b"reovim_client_module_annotation_column_width",
                )
                .ok()
                .map(|s| *s);
            let transform_line = library
                .get::<ClientTransformLineFn>(b"reovim_client_module_transform_line")
                .ok()
                .map(|s| *s);
            let free_transformed_line = library
                .get::<ClientFreeTransformedLineFn>(b"reovim_client_module_free_transformed_line")
                .ok()
                .map(|s| *s);
            let map_cursor_column = library
                .get::<ClientMapCursorColumnFn>(b"reovim_client_module_map_cursor_column")
                .ok()
                .map(|s| *s);
            let fold_ranges = library
                .get::<ClientFoldRangesFn>(b"reovim_client_module_fold_ranges")
                .ok()
                .map(|s| *s);
            let virtual_lines = library
                .get::<ClientVirtualLinesFn>(b"reovim_client_module_virtual_lines")
                .ok()
                .map(|s| *s);
            let inline_decorations = library
                .get::<ClientInlineDecorationsFn>(b"reovim_client_module_inline_decorations")
                .ok()
                .map(|s| *s);
            let cursor_position = library
                .get::<ClientCursorPositionFn>(b"reovim_client_module_cursor_position")
                .ok()
                .map(|s| *s);
            let classify_token = library
                .get::<ClientClassifyTokenFn>(b"reovim_client_module_classify_token")
                .ok()
                .map(|s| *s);
            let on_capabilities_changed = library
                .get::<ClientOnCapabilitiesChangedFn>(
                    b"reovim_client_module_on_capabilities_changed",
                )
                .ok()
                .map(|s| *s);
            let on_theme_changed = library
                .get::<ClientOnThemeChangedFn>(b"reovim_client_module_on_theme_changed")
                .ok()
                .map(|s| *s);

            let ffi = ClientFfiSymbols {
                init: *init_sym,
                exit: *exit_sym,
                destroy: *destroy_sym,
                on_all_loaded,
                on_notification,
                on_mode_change,
                on_cursor_update,
                on_buffer_focus,
                on_buffer_update,
                on_option_changed,
                tick,
                has_chrome,
                has_buffer_contrib,
                has_annotations,
                chrome_position,
                chrome_requested_size,
                chrome_priority,
                chrome_z_order,
                buffer_contrib_priority,
                annotation_priority,
                chrome_render,
                annotate,
                annotation_column_width,
                transform_line,
                free_transformed_line,
                map_cursor_column,
                fold_ranges,
                virtual_lines,
                inline_decorations,
                cursor_position,
                classify_token,
                on_capabilities_changed,
                on_theme_changed,
            };

            Ok(Self::from_dynamic(library, path.to_path_buf(), probe, ptr, ffi))
        }
    }

    /// Module kind identifier.
    #[must_use]
    pub const fn kind(&self) -> &'static str {
        self.kind
    }

    /// Human-readable module name.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.name
    }

    /// Module version.
    #[must_use]
    pub const fn version(&self) -> Version {
        self.version
    }

    /// Whether this handle wraps a static module.
    #[must_use]
    pub const fn is_static(&self) -> bool {
        self.static_module.is_some()
    }

    /// Whether this handle wraps a dynamic module.
    #[must_use]
    pub const fn is_dynamic(&self) -> bool {
        self.dynamic_ptr.is_some()
    }

    /// Get the static module reference (if static).
    #[must_use]
    pub fn as_module(&self) -> Option<&dyn ClientModule> {
        self.static_module.as_deref()
    }

    /// Get the static module mutable reference (if static).
    pub fn as_module_mut(&mut self) -> Option<&mut dyn ClientModule> {
        self.static_module.as_deref_mut()
    }

    /// Required dependencies (static slice — safe to pass through FFI wrappers).
    #[must_use]
    pub const fn dependencies(&self) -> &'static [&'static str] {
        self.deps
    }

    /// Optional dependencies (static slice — safe to pass through FFI wrappers).
    #[must_use]
    pub const fn optional_dependencies(&self) -> &'static [&'static str] {
        self.optional_deps
    }

    /// Path to the `.so` file (dynamic modules only).
    #[must_use]
    pub const fn path(&self) -> Option<&PathBuf> {
        self.path.as_ref()
    }

    /// Initialize the module.
    pub fn init(&mut self, ctx: &ModuleContext) -> ProbeResult {
        if let Some(module) = &mut self.static_module {
            return module.init(ctx);
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            let ctx_ptr = std::ptr::from_ref(ctx).cast::<c_void>();
            // SAFETY: ptr is from entry(), ctx_ptr points to valid ModuleContext
            let code = unsafe { (ffi.init)(ptr, ctx_ptr) };
            return match code {
                0 => ProbeResult::Success,
                1 => ProbeResult::Defer("dynamic module deferred".to_string()),
                _ => ProbeResult::Failed(ClientModuleError::init_failed(
                    format!("dynamic init returned code {code}"),
                    None,
                )),
            };
        }

        ProbeResult::Failed(ClientModuleError::init_failed(
            "handle has neither static nor dynamic module",
            None,
        ))
    }

    /// Shut down the module.
    ///
    /// # Errors
    ///
    /// Returns an error if the module's exit fails.
    pub fn exit(&mut self) -> Result<(), ClientModuleError> {
        if let Some(module) = &mut self.static_module {
            return module.exit();
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // SAFETY: ptr is from entry()
            let code = unsafe { (ffi.exit)(ptr) };
            return if code == 0 {
                Ok(())
            } else {
                Err(ClientModuleError::exit_failed(format!("dynamic exit returned code {code}")))
            };
        }

        Ok(())
    }

    /// Lifecycle hook after all modules are loaded.
    pub fn on_all_loaded(&mut self, ctx: &ModuleContext) {
        if let Some(module) = &mut self.static_module {
            module.on_all_loaded(ctx);
            return;
        }

        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(on_all_loaded) = ffi.on_all_loaded
        {
            let ctx_ptr = std::ptr::from_ref(ctx).cast::<c_void>();
            // SAFETY: ptr is from entry(), ctx_ptr points to valid ModuleContext
            unsafe {
                on_all_loaded(ptr, ctx_ptr);
            }
        }
    }

    // =========================================================================
    // Event dispatch
    // =========================================================================

    /// Handle a server notification (JSON data).
    pub fn on_notification(&mut self, data: &str) {
        if let Some(module) = &mut self.static_module {
            module.on_notification(data);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_notification
        {
            // SAFETY: ptr is from entry(), data is a valid UTF-8 slice
            unsafe {
                (f)(ptr, data.as_ptr(), data.len());
            }
        }
    }

    /// Handle a mode change (e.g., "normal", "insert", "visual").
    pub fn on_mode_change(&mut self, mode: &str) {
        if let Some(module) = &mut self.static_module {
            module.on_mode_change(mode);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_mode_change
        {
            // SAFETY: ptr is from entry(), mode is a valid UTF-8 slice
            unsafe {
                (f)(ptr, mode.as_ptr(), mode.len());
            }
        }
    }

    /// Handle a cursor position change.
    pub fn on_cursor_update(&mut self, buffer_id: BufferId, line: usize, col: usize) {
        if let Some(module) = &mut self.static_module {
            module.on_cursor_update(buffer_id, line, col);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_cursor_update
        {
            // SAFETY: ptr is from entry()
            unsafe {
                (f)(ptr, buffer_id.0, line, col);
            }
        }
    }

    /// Handle focus change to a different buffer.
    pub fn on_buffer_focus(&mut self, buffer_id: BufferId) {
        if let Some(module) = &mut self.static_module {
            module.on_buffer_focus(buffer_id);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_buffer_focus
        {
            // SAFETY: ptr is from entry()
            unsafe {
                (f)(ptr, buffer_id.0);
            }
        }
    }

    /// Handle a buffer content update.
    ///
    /// For dynamic modules, only scalar metadata is passed (`buffer_id`,
    /// revision, `changed_start`, `changed_end`, `total_lines`). The
    /// `new_lines` field cannot cross FFI as a `Vec<String>`. Dynamic modules
    /// that need content can re-fetch via `ServerHandle`.
    pub fn on_buffer_update(&mut self, event: &BufferUpdateEvent) {
        if let Some(module) = &mut self.static_module {
            module.on_buffer_update(event);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_buffer_update
        {
            // SAFETY: ptr is from entry()
            unsafe {
                (f)(
                    ptr,
                    event.buffer_id.0,
                    event.revision,
                    event.changed_range.start,
                    event.changed_range.end,
                    event.total_lines,
                );
            }
        }
    }

    /// Handle an option value change.
    ///
    /// For dynamic modules, the value is encoded as (tag, i64, `str_ptr`, `str_len`):
    /// - tag 0 = Bool (i64 != 0)
    /// - tag 1 = Integer (i64 value)
    /// - tag 2 = String (`str_ptr` + `str_len`)
    pub fn on_option_changed(&mut self, name: &str, value: &OptionValue) {
        if let Some(module) = &mut self.static_module {
            module.on_option_changed(name, value);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_option_changed
        {
            let (tag, i64_val, str_ptr, str_len) = match value {
                OptionValue::Bool(b) => (0i32, i64::from(*b), std::ptr::null(), 0),
                OptionValue::Integer(i) => (1, *i, std::ptr::null(), 0),
                OptionValue::String(s) => (2, 0, s.as_ptr(), s.len()),
            };
            // SAFETY: ptr is from entry(), name and string value are valid UTF-8 slices
            unsafe {
                (f)(ptr, name.as_ptr(), name.len(), tag, i64_val, str_ptr, str_len);
            }
        }
    }

    /// Periodic tick. Returns `true` if state changed and a redraw is needed.
    pub fn tick(&mut self) -> bool {
        if let Some(module) = &mut self.static_module {
            return module.tick();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.tick
        {
            // SAFETY: ptr is from entry()
            let code = unsafe { (f)(ptr) };
            return code == 1;
        }
        false
    }

    // =========================================================================
    // Role declaration dispatch
    // =========================================================================

    /// Whether this module contributes chrome.
    #[must_use]
    pub fn has_chrome(&self) -> bool {
        if let Some(module) = &self.static_module {
            return module.has_chrome();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.has_chrome
        {
            // SAFETY: ptr is from entry()
            let code = unsafe { (f)(ptr) };
            return code == 1;
        }
        false
    }

    /// Whether this module contributes to buffer rendering.
    #[must_use]
    pub fn has_buffer_contrib(&self) -> bool {
        if let Some(module) = &self.static_module {
            return module.has_buffer_contrib();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.has_buffer_contrib
        {
            // SAFETY: ptr is from entry()
            let code = unsafe { (f)(ptr) };
            return code == 1;
        }
        false
    }

    /// Whether this module contributes gutter annotations.
    #[must_use]
    pub fn has_annotations(&self) -> bool {
        if let Some(module) = &self.static_module {
            return module.has_annotations();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.has_annotations
        {
            // SAFETY: ptr is from entry()
            let code = unsafe { (f)(ptr) };
            return code == 1;
        }
        false
    }

    /// Where this module's chrome is rendered.
    #[must_use]
    pub fn chrome_position(&self) -> ChromePosition {
        if let Some(module) = &self.static_module {
            return module.chrome_position();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.chrome_position
        {
            // SAFETY: ptr is from entry()
            let code = unsafe { (f)(ptr) };
            return match code {
                0 => ChromePosition::Top,
                2 => ChromePosition::Left,
                3 => ChromePosition::Right,
                4 => ChromePosition::Overlay,
                _ => ChromePosition::Bottom, // 1 or unknown
            };
        }
        ChromePosition::Bottom
    }

    /// Requested size (height for Top/Bottom, width for Left/Right).
    #[must_use]
    pub fn chrome_requested_size(&self, caps: &dyn PlatformCapabilities) -> u16 {
        if let Some(module) = &self.static_module {
            return module.chrome_requested_size(caps);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.chrome_requested_size
        {
            let ffi_caps = FfiPlatformCaps::snapshot(caps);
            // SAFETY: ptr is from entry(); ffi_caps outlives the call.
            return unsafe { (f)(ptr, &raw const ffi_caps) };
        }
        1
    }

    /// Priority for chrome allocation (higher = allocated first).
    #[must_use]
    pub fn chrome_priority(&self) -> u16 {
        if let Some(module) = &self.static_module {
            return module.chrome_priority();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.chrome_priority
        {
            // SAFETY: ptr is from entry()
            return unsafe { (f)(ptr) };
        }
        0
    }

    /// Z-order for overlay chrome (higher = drawn on top).
    #[must_use]
    pub fn chrome_z_order(&self) -> u16 {
        if let Some(module) = &self.static_module {
            return module.chrome_z_order();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.chrome_z_order
        {
            // SAFETY: ptr is from entry()
            return unsafe { (f)(ptr) };
        }
        0
    }

    /// Priority for buffer contribution dispatch (higher = checked first).
    #[must_use]
    pub fn buffer_contrib_priority(&self) -> u16 {
        if let Some(module) = &self.static_module {
            return module.buffer_contrib_priority();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.buffer_contrib_priority
        {
            // SAFETY: ptr is from entry()
            return unsafe { (f)(ptr) };
        }
        0
    }

    /// Priority for annotation ordering (higher = leftmost in gutter).
    #[must_use]
    pub fn annotation_priority(&self) -> u16 {
        if let Some(module) = &self.static_module {
            return module.annotation_priority();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.annotation_priority
        {
            // SAFETY: ptr is from entry()
            return unsafe { (f)(ptr) };
        }
        0
    }

    // =========================================================================
    // Render dispatch (#723)
    // =========================================================================
    //
    // Each method below:
    //   1. If static: delegate directly.
    //   2. If dynamic AND symbol resolved: convert Rust args -> Ffi args,
    //      call through the cached function pointer, convert return.
    //   3. Otherwise: fall through to the trait default.
    //
    // Host code is the sole caller; modules never invoke these methods.
    // The SAFETY invariants on each `unsafe` block derive from the
    // contracts documented at `ClientFfiSymbols` and the matching
    // trampolines in `declare_client_module!`.

    /// Render chrome into the given surface region.
    pub fn chrome_render(
        &self,
        surface: &mut dyn ChromeSurface,
        bounds: Rect,
        caps: &dyn PlatformCapabilities,
    ) {
        if let Some(module) = &self.static_module {
            module.chrome_render(surface, bounds, caps);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.chrome_render
        {
            let mut host = FfiRenderSurfaceHost::new(surface);
            let mut ffi_surface = FfiRenderSurface::from_host(&mut host);
            let ffi_caps = FfiPlatformCaps::snapshot(caps);
            // SAFETY: ptr is from entry(); host + ffi_caps outlive the call.
            unsafe {
                (f)(ptr, std::ptr::from_mut(&mut ffi_surface), bounds, &raw const ffi_caps);
            }
        }
    }

    /// Return the annotation gutter cell for `line`, if the module provides one.
    #[must_use]
    pub fn annotate(&self, line: usize, ctx: &AnnotationContext) -> Option<GutterCell> {
        if let Some(module) = &self.static_module {
            return module.annotate(line, ctx);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.annotate
        {
            let ffi_ctx = FfiAnnotationContext::from_ctx(ctx);
            // SAFETY: ptr is from entry(); ffi_ctx outlives the call.
            let cell = unsafe { (f)(ptr, line, &raw const ffi_ctx) };
            return cell.into_cell();
        }
        None
    }

    /// Annotation column width.
    #[must_use]
    pub fn annotation_column_width(
        &self,
        ctx: &AnnotationContext,
        caps: &dyn PlatformCapabilities,
    ) -> ColumnWidth {
        if let Some(module) = &self.static_module {
            return module.annotation_column_width(ctx, caps);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.annotation_column_width
        {
            let ffi_ctx = FfiAnnotationContext::from_ctx(ctx);
            let ffi_caps = FfiPlatformCaps::snapshot(caps);
            // SAFETY: ptr is from entry(); ffi_ctx + ffi_caps outlive the call.
            let w = unsafe { (f)(ptr, &raw const ffi_ctx, &raw const ffi_caps) };
            return w.into_width();
        }
        ColumnWidth::Fixed(0)
    }

    /// Transform a buffer line before rendering.
    #[must_use]
    pub fn transform_line(
        &self,
        buf: BufferId,
        line: usize,
        text: &str,
    ) -> Option<TransformedLine> {
        if let Some(module) = &self.static_module {
            return module.transform_line(buf, line, text);
        }
        let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, self.ffi.as_ref()) else {
            return None;
        };
        let (Some(tl_fn), Some(free_fn)) = (ffi.transform_line, ffi.free_transformed_line) else {
            return None;
        };
        // SAFETY: ptr is from entry(); text borrowed for call duration.
        let tl_ptr = unsafe { (tl_fn)(ptr, buf.0, line, text.as_ptr(), text.len()) };
        if tl_ptr.is_null() {
            return None;
        }
        // SAFETY: tl_ptr was allocated by the module's transform_line
        // trampoline (from_rust) in module allocator context. read_owned
        // copies the contents into host-owned memory WITHOUT taking
        // ownership of the module-allocated buffers, then we immediately
        // call the module's free trampoline to release them.
        let owned = unsafe { FfiTransformedLine::read_owned(tl_ptr) };
        unsafe { (free_fn)(tl_ptr) };
        Some(owned)
    }

    /// Map a cursor column to a display column.
    #[must_use]
    pub fn map_cursor_column(&self, buf: BufferId, line: usize, col: usize) -> Option<u16> {
        if let Some(module) = &self.static_module {
            return module.map_cursor_column(buf, line, col);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.map_cursor_column
        {
            // SAFETY: ptr is from entry().
            let v = unsafe { (f)(ptr, buf.0, line, col) };
            if v < 0 {
                return None;
            }
            #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
            return Some(v as u16);
        }
        None
    }

    /// Fold ranges owned by the module.
    ///
    /// For dynamic modules, the returned Vec is copied out of the module's
    /// thread-local cache (the cache is overwritten on the next call).
    #[must_use]
    pub fn fold_ranges(&self) -> Vec<(usize, usize)> {
        if let Some(module) = &self.static_module {
            return module.fold_ranges().to_vec();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.fold_ranges
        {
            let mut out_ptr: *const FfiFoldRange = std::ptr::null();
            let mut out_len: usize = 0;
            // SAFETY: ptr is from entry(); out_ptr/out_len owned on host stack.
            unsafe {
                (f)(ptr, &raw mut out_ptr, &raw mut out_len);
            }
            if out_ptr.is_null() || out_len == 0 {
                return Vec::new();
            }
            // SAFETY: out_ptr points to the module's thread-local cache
            // which is valid until the next fold_ranges call on the same
            // thread. We copy immediately.
            let slice = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
            return slice.iter().map(|r| (r.start_line, r.line_count)).collect();
        }
        Vec::new()
    }

    /// Virtual lines emitted by the module.
    #[must_use]
    pub fn virtual_lines(&self) -> Vec<VirtualLine> {
        if let Some(module) = &self.static_module {
            return module.virtual_lines().to_vec();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.virtual_lines
        {
            let mut out_ptr: *const FfiVirtualLine = std::ptr::null();
            let mut out_len: usize = 0;
            // SAFETY: ptr is from entry(); out_ptr/out_len on host stack.
            unsafe {
                (f)(ptr, &raw mut out_ptr, &raw mut out_len);
            }
            if out_ptr.is_null() || out_len == 0 {
                return Vec::new();
            }
            // SAFETY: same thread-local invariant as fold_ranges.
            let slice = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
            return slice.iter().map(|v| (*v).into_rust()).collect();
        }
        Vec::new()
    }

    /// Inline decorations for a line.
    #[must_use]
    pub fn inline_decorations(&self, line: usize) -> Vec<InlineDecoration> {
        if let Some(module) = &self.static_module {
            return module.inline_decorations(line).to_vec();
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.inline_decorations
        {
            let mut out_ptr: *const FfiInlineDecoration = std::ptr::null();
            let mut out_len: usize = 0;
            // SAFETY: ptr is from entry(); out_ptr/out_len on host stack.
            unsafe {
                (f)(ptr, line, &raw mut out_ptr, &raw mut out_len);
            }
            if out_ptr.is_null() || out_len == 0 {
                return Vec::new();
            }
            // SAFETY: same thread-local invariant as fold_ranges.
            let slice = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
            return slice.iter().map(|d| (*d).into_deco()).collect();
        }
        Vec::new()
    }

    /// Module-overridden cursor position, if any.
    #[must_use]
    pub fn cursor_position(&self, w: u16, h: u16) -> Option<(u16, u16)> {
        if let Some(module) = &self.static_module {
            return module.cursor_position(w, h);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.cursor_position
        {
            let mut col: u16 = 0;
            let mut row: u16 = 0;
            // SAFETY: ptr is from entry(); col/row on host stack.
            let has = unsafe { (f)(ptr, w, h, &raw mut col, &raw mut row) };
            if has == 1 {
                return Some((col, row));
            }
        }
        None
    }

    /// Classify a token category for rendering behavior.
    #[must_use]
    pub fn classify_token(&self, category: &str) -> Option<RenderBehavior> {
        if let Some(module) = &self.static_module {
            return module.classify_token(category);
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.classify_token
        {
            // SAFETY: ptr is from entry(); category borrowed for call.
            let rb = unsafe { (f)(ptr, category.as_ptr(), category.len()) };
            return rb.into_option();
        }
        None
    }

    /// Handle platform capabilities change.
    pub fn on_capabilities_changed(&mut self, caps: &dyn PlatformCapabilities) {
        if let Some(module) = &mut self.static_module {
            module.on_capabilities_changed(caps);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_capabilities_changed
        {
            let ffi_caps = FfiPlatformCaps::snapshot(caps);
            // SAFETY: ptr is from entry(); ffi_caps outlives the call.
            unsafe {
                (f)(ptr, &raw const ffi_caps);
            }
        }
    }

    /// Handle theme change.
    pub fn on_theme_changed(&mut self, theme: &dyn ThemeProvider) {
        if let Some(module) = &mut self.static_module {
            module.on_theme_changed(theme);
            return;
        }
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi)
            && let Some(f) = ffi.on_theme_changed
        {
            let host = FfiThemeProviderHost::new(theme);
            let ffi_theme = FfiThemeProvider::from_host(&host);
            // SAFETY: ptr is from entry(); host + ffi_theme outlive the call.
            unsafe {
                (f)(ptr, &raw const ffi_theme);
            }
        }
    }
}

// Dynamic cleanup path requires a real .so module.
#[cfg_attr(coverage_nightly, coverage(off))]
impl Drop for ClientModuleHandle {
    fn drop(&mut self) {
        // For dynamic modules: call destroy before unloading library
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr.take(), &self.ffi) {
            // SAFETY: ptr is from entry(), destroy frees it
            unsafe {
                (ffi.destroy)(ptr);
            }
        }
        // Library is dropped automatically, unloading the .so
    }
}

impl std::fmt::Debug for ClientModuleHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ClientModuleHandle")
            .field("kind", &self.kind)
            .field("name", &self.name)
            .field("version", &self.version)
            .field("is_static", &self.is_static())
            .field("is_dynamic", &self.is_dynamic())
            .field("path", &self.path)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
#[path = "handle_tests.rs"]
mod tests;
