[package]
name = "reovim-tui-mod-tetromino"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Tetromino game native module for reovim TUI"
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
reovim-client-driver = { workspace = true }
serde_json = { workspace = true }
