//! Module handle for loaded modules.
//!
//! Provides a unified interface for both static and dynamic modules.

use std::{
    ffi::c_void,
    path::{Path, PathBuf},
};

use {
    libloading::Library,
    reovim_kernel::api::v1::{
        Module, ModuleContext, ModuleError, ModuleId, ModuleProbe, ProbeResult, Version,
    },
};

/// FFI function types from `declare_module!` macro.
///
/// These match the symbols generated by the kernel's proc-macro.
pub(crate) type ProbeFn = unsafe extern "C" fn() -> ModuleProbe;
pub(crate) type EntryFn = unsafe extern "C" fn() -> *mut c_void;
pub(crate) type InitFn = unsafe extern "C" fn(*mut c_void, *const c_void) -> i32;
pub(crate) type ExitFn = unsafe extern "C" fn(*mut c_void) -> i32;
pub(crate) type DestroyFn = unsafe extern "C" fn(*mut c_void);

// Hot reload FFI types (Phase 4.6 addition)
pub(crate) type SupportsHotReloadFn = unsafe extern "C" fn(*const c_void) -> i32;
pub(crate) type SaveStateFn = unsafe extern "C" fn(*const c_void, *mut *mut u8, *mut usize) -> i32;
pub(crate) type RestoreStateFn = unsafe extern "C" fn(*mut c_void, *const u8, usize) -> i32;
pub(crate) type FreeStateFn = unsafe extern "C" fn(*mut u8, usize);

/// Maximum allowed state size for hot reload (16 MiB).
///
/// This limit prevents memory exhaustion from malicious or buggy modules
/// returning excessively large state buffers during hot reload.
const MAX_STATE_SIZE: usize = 16 * 1024 * 1024;

/// Handle to a loaded module.
///
/// # FFI Safety
///
/// For dynamic modules, we keep opaque pointers (`*mut c_void`) instead of
/// `Box<dyn Module>` because fat pointers cannot cross FFI boundaries.
/// All lifecycle operations go through FFI trampolines.
pub struct ModuleHandle {
    /// Unique identifier (from probe).
    id: ModuleId,

    /// Module metadata (from probe, no allocation).
    probe: ModuleProbe,

    /// For STATIC modules: owned Box.
    static_module: Option<Box<dyn Module>>,

    /// For DYNAMIC modules: opaque pointer (FFI).
    dynamic_ptr: Option<*mut c_void>,

    /// Library handle (keeps .so loaded).
    library: Option<Library>,

    /// Source path (for hot reload).
    path: Option<PathBuf>,

    /// Cached FFI symbols (avoids repeated lookup).
    ffi: Option<FfiSymbols>,
}

// Safety: ModuleHandle is Send+Sync because:
// - static_module is Send+Sync (Module trait requires it)
// - dynamic_ptr is only accessed through FFI trampolines
// - Library handle is thread-safe for keeping library loaded
unsafe impl Send for ModuleHandle {}
unsafe impl Sync for ModuleHandle {}

/// Cached FFI symbols for dynamic modules.
pub(crate) struct FfiSymbols {
    pub(crate) init: InitFn,
    pub(crate) exit: ExitFn,
    pub(crate) destroy: DestroyFn,
    // Optional hot reload symbols (Phase 4.6 addition)
    pub(crate) supports_hot_reload: Option<SupportsHotReloadFn>,
    pub(crate) save_state: Option<SaveStateFn>,
    pub(crate) restore_state: Option<RestoreStateFn>,
    pub(crate) free_state: Option<FreeStateFn>,
}

/// Result of `init()` call.
#[derive(Debug, Clone)]
pub enum InitResult {
    /// Module initialized successfully.
    Success,
    /// Module deferred initialization (retry later).
    Defer(String),
}

impl ModuleHandle {
    /// Create a handle for a static (compile-time linked) module.
    pub fn from_static<M: Module>(module: M) -> Self {
        let probe = ModuleProbe::new(
            module.id().as_str(),
            module.name(),
            module.version(),
            module.api_version(),
        );
        let id = module.id();

        Self {
            id,
            probe,
            static_module: Some(Box::new(module)),
            dynamic_ptr: None,
            library: None,
            path: None,
            ffi: None,
        }
    }

    /// Create a handle from an already-boxed module.
    ///
    /// Use this when you have a `Box<dyn Module>` instead of a concrete type.
    pub fn from_boxed(module: Box<dyn Module>) -> Self {
        let probe = ModuleProbe::new(
            module.id().as_str(),
            module.name(),
            module.version(),
            module.api_version(),
        );
        let id = module.id();

        Self {
            id,
            probe,
            static_module: Some(module),
            dynamic_ptr: None,
            library: None,
            path: None,
            ffi: None,
        }
    }

    /// Create a handle for a dynamic (runtime loaded) module.
    ///
    /// # Safety
    ///
    /// - The library must be ABI-compatible
    /// - The library must have been built with matching `declare_module!` macro
    #[allow(clippy::large_types_passed_by_value)] // ModuleProbe is FFI-returned by value
    pub(crate) unsafe fn from_dynamic(
        library: Library,
        path: PathBuf,
        probe: ModuleProbe,
        module_ptr: *mut c_void,
        ffi: FfiSymbols,
    ) -> Self {
        let id = ModuleId::from_string(probe.id_str().to_owned());

        Self {
            id,
            probe,
            static_module: None,
            dynamic_ptr: Some(module_ptr),
            library: Some(library),
            path: Some(path),
            ffi: Some(ffi),
        }
    }

    /// Initialize the module via FFI trampoline.
    ///
    /// # FFI Return codes
    ///
    /// - `0` = Success (`ProbeResult::Success`)
    /// - `1` = Defer (`ProbeResult::Defer`) - retry later
    /// - `-1` = Failed (`ProbeResult::Failed`)
    /// - `-2` = Panic occurred
    pub fn init(&mut self, ctx: &ModuleContext) -> Result<InitResult, ModuleError> {
        if let Some(ref mut module) = self.static_module {
            // Static module: direct call
            match module.init(ctx) {
                ProbeResult::Success => Ok(InitResult::Success),
                ProbeResult::Defer(reason) => Ok(InitResult::Defer(reason)),
                ProbeResult::Failed(err) => Err(err),
            }
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            if ptr.is_null() {
                return Err(ModuleError::InitFailed("module pointer is null".into()));
            }

            // Dynamic module: FFI trampoline
            // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
            let ctx_ptr = ctx as *const ModuleContext as *const c_void;
            let result = unsafe { (ffi.init)(ptr, ctx_ptr) };

            match result {
                0 => Ok(InitResult::Success),
                1 => Ok(InitResult::Defer("deferred by module".into())),
                -1 => Err(ModuleError::InitFailed("init returned error".into())),
                -2 => Err(ModuleError::InitFailed("panic in module init".into())),
                code => Err(ModuleError::InitFailed(format!("unknown code: {code}"))),
            }
        } else {
            Err(ModuleError::NotLoaded(self.id.clone()))
        }
    }

    /// Call module exit via FFI trampoline.
    pub fn exit(&mut self) -> Result<(), ModuleError> {
        if let Some(ref mut module) = self.static_module {
            module.exit()
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            if ptr.is_null() {
                return Err(ModuleError::InitFailed("module pointer is null".into()));
            }

            // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
            let result = unsafe { (ffi.exit)(ptr) };
            match result {
                0 => Ok(()),
                -1 => Err(ModuleError::InitFailed("exit returned error".into())),
                -2 => Err(ModuleError::InitFailed("panic in module exit".into())),
                code => Err(ModuleError::InitFailed(format!("unknown code: {code}"))),
            }
        } else {
            Err(ModuleError::NotLoaded(self.id.clone()))
        }
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Get module ID.
    #[must_use]
    pub fn id(&self) -> &ModuleId {
        &self.id
    }

    /// Get module name from probe.
    #[must_use]
    pub fn name(&self) -> &str {
        self.probe.name_str()
    }

    /// Get module version from probe.
    #[must_use]
    pub fn version(&self) -> Version {
        self.probe.version
    }

    /// Get module API version from probe.
    #[must_use]
    pub fn api_version(&self) -> Version {
        self.probe.api_version
    }

    /// Get module path (for dynamic modules).
    #[must_use]
    pub fn path(&self) -> Option<&Path> {
        self.path.as_deref()
    }

    /// Check if this is a static module.
    #[must_use]
    pub fn is_static(&self) -> bool {
        self.static_module.is_some()
    }

    /// Check if this is a dynamic module.
    #[must_use]
    pub fn is_dynamic(&self) -> bool {
        self.dynamic_ptr.is_some()
    }

    /// Get static module reference (for static modules only).
    #[must_use]
    pub fn as_module(&self) -> Option<&dyn Module> {
        self.static_module.as_deref()
    }

    /// Get mutable static module reference.
    #[must_use]
    pub fn as_module_mut(&mut self) -> Option<&mut dyn Module> {
        self.static_module.as_deref_mut()
    }

    /// Get module dependencies.
    ///
    /// For static modules, calls the trait method directly.
    /// For dynamic modules, reads from probe metadata (populated at build time).
    #[must_use]
    pub fn dependencies(&self) -> Vec<ModuleId> {
        if let Some(ref module) = self.static_module {
            module.dependencies()
        } else {
            // Dynamic modules: use probe metadata
            self.probe.required_deps()
        }
    }

    /// Get optional dependencies.
    ///
    /// For static modules, calls the trait method directly.
    /// For dynamic modules, reads from probe metadata (populated at build time).
    #[must_use]
    pub fn optional_dependencies(&self) -> Vec<ModuleId> {
        if let Some(ref module) = self.static_module {
            module.optional_dependencies()
        } else {
            // Dynamic modules: use probe metadata
            self.probe.optional_deps()
        }
    }

    /// Check if module supports hot reload.
    #[must_use]
    pub fn supports_hot_reload(&self) -> bool {
        if let Some(ref module) = self.static_module {
            module.supports_hot_reload()
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Dynamic modules: use FFI trampoline if available
            if let Some(supports_fn) = ffi.supports_hot_reload {
                // SAFETY: ptr is valid (checked), supports_fn is from loader
                let result = unsafe { supports_fn(ptr) };
                result == 1
            } else {
                false
            }
        } else {
            false
        }
    }

    /// Save module state (for hot reload).
    ///
    /// For dynamic modules, uses FFI trampoline. Caller is responsible for
    /// freeing the returned state (automatically handled by `Box`).
    ///
    /// # Size Limit
    ///
    /// State buffers larger than 16 MiB are rejected and freed to prevent
    /// memory exhaustion from malicious or buggy modules.
    #[must_use]
    pub fn save_state(&self) -> Option<Box<[u8]>> {
        if let Some(ref module) = self.static_module {
            let state = module.save_state()?;
            // Enforce size limit for static modules too
            if state.len() > MAX_STATE_SIZE {
                tracing::warn!(
                    module_id = %self.id,
                    size = state.len(),
                    limit = MAX_STATE_SIZE,
                    "state exceeds size limit, discarding"
                );
                return None;
            }
            Some(state)
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Dynamic modules: use FFI trampoline if available
            if let Some(save_fn) = ffi.save_state {
                let mut out_ptr: *mut u8 = std::ptr::null_mut();
                let mut out_len: usize = 0;

                // SAFETY: ptr is valid, out_ptr/out_len are valid stack addresses
                let result = unsafe { save_fn(ptr, &raw mut out_ptr, &raw mut out_len) };

                if result == 0 && !out_ptr.is_null() && out_len > 0 {
                    // Security: Enforce size limit to prevent memory exhaustion
                    if out_len > MAX_STATE_SIZE {
                        tracing::warn!(
                            module_id = %self.id,
                            size = out_len,
                            limit = MAX_STATE_SIZE,
                            "state exceeds size limit, freeing and discarding"
                        );
                        // Free the oversized buffer via FFI
                        if let Some(free_fn) = ffi.free_state {
                            // SAFETY: out_ptr was allocated by save_fn, out_len is its size
                            unsafe { free_fn(out_ptr, out_len) };
                        }
                        // Note: If free_fn is None, we intentionally leak rather than
                        // risk double-free or OOM from accepting oversized state
                        return None;
                    }

                    // SAFETY: save_fn allocated this with Box::into_raw
                    let slice = unsafe {
                        Box::from_raw(std::ptr::slice_from_raw_parts_mut(out_ptr, out_len))
                    };
                    Some(slice)
                } else {
                    None
                }
            } else {
                None
            }
        } else {
            None
        }
    }

    /// Restore module state (for hot reload).
    ///
    /// For dynamic modules, uses FFI trampoline.
    pub fn restore_state(&mut self, state: &[u8]) -> Result<(), ModuleError> {
        if let Some(ref mut module) = self.static_module {
            module.restore_state(state)
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Dynamic modules: use FFI trampoline if available
            if let Some(restore_fn) = ffi.restore_state {
                // SAFETY: ptr is valid, state is a valid slice
                let result = unsafe { restore_fn(ptr, state.as_ptr(), state.len()) };
                match result {
                    0 => Ok(()),
                    -1 => Err(ModuleError::InitFailed("restore_state failed".into())),
                    -2 => Err(ModuleError::InitFailed("panic in restore_state".into())),
                    code => Err(ModuleError::InitFailed(format!("unknown code: {code}"))),
                }
            } else {
                Err(ModuleError::InitFailed(
                    "state restore not supported for this dynamic module".into(),
                ))
            }
        } else {
            Err(ModuleError::NotLoaded(self.id.clone()))
        }
    }
}

impl Drop for ModuleHandle {
    fn drop(&mut self) {
        // For dynamic modules: call destroy trampoline
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr.take(), &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            // Note: proc-macro's destroy also checks for null, but we check here too
            if !ptr.is_null() {
                // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
                unsafe { (ffi.destroy)(ptr) };
            }
        }
        // Library is dropped automatically, unloading the .so
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestModule {
        initialized: bool,
    }

    impl Module for TestModule {
        fn id(&self) -> ModuleId {
            ModuleId::new("test-module")
        }

        fn name(&self) -> &'static str {
            "Test Module"
        }

        fn version(&self) -> Version {
            Version::new(1, 0, 0)
        }

        fn init(&mut self, _ctx: &ModuleContext) -> ProbeResult {
            self.initialized = true;
            ProbeResult::Success
        }

        fn exit(&mut self) -> Result<(), ModuleError> {
            self.initialized = false;
            Ok(())
        }
    }

    #[test]
    fn test_static_handle_creation() {
        let module = TestModule { initialized: false };
        let handle = ModuleHandle::from_static(module);

        assert!(handle.is_static());
        assert!(!handle.is_dynamic());
        assert_eq!(handle.id().as_str(), "test-module");
        assert_eq!(handle.name(), "Test Module");
    }

    #[test]
    fn test_static_handle_init() {
        let module = TestModule { initialized: false };
        let mut handle = ModuleHandle::from_static(module);
        let ctx = ModuleContext::default();

        let result = handle.init(&ctx);
        assert!(matches!(result, Ok(InitResult::Success)));
    }

    #[test]
    fn test_static_handle_exit() {
        let module = TestModule { initialized: true };
        let mut handle = ModuleHandle::from_static(module);

        let result = handle.exit();
        assert!(result.is_ok());
    }

    // ========================================================================
    // Hot Reload Tests
    // ========================================================================

    /// Test module with hot reload support.
    struct HotReloadModule {
        counter: u32,
    }

    impl Module for HotReloadModule {
        fn id(&self) -> ModuleId {
            ModuleId::new("hot-reload-module")
        }

        fn name(&self) -> &'static str {
            "Hot Reload Module"
        }

        fn version(&self) -> Version {
            Version::new(1, 0, 0)
        }

        fn init(&mut self, _ctx: &ModuleContext) -> ProbeResult {
            ProbeResult::Success
        }

        fn exit(&mut self) -> Result<(), ModuleError> {
            Ok(())
        }

        fn supports_hot_reload(&self) -> bool {
            true
        }

        fn save_state(&self) -> Option<Box<[u8]>> {
            // Simple serialization: counter as 4 bytes
            Some(self.counter.to_le_bytes().to_vec().into_boxed_slice())
        }

        fn restore_state(&mut self, state: &[u8]) -> Result<(), ModuleError> {
            if state.len() != 4 {
                return Err(ModuleError::InitFailed("invalid state size".into()));
            }
            self.counter = u32::from_le_bytes([state[0], state[1], state[2], state[3]]);
            Ok(())
        }
    }

    #[test]
    fn test_static_module_supports_hot_reload() {
        let module = HotReloadModule { counter: 42 };
        let handle = ModuleHandle::from_static(module);

        assert!(handle.supports_hot_reload());
    }

    #[test]
    fn test_static_module_no_hot_reload_support() {
        let module = TestModule { initialized: false };
        let handle = ModuleHandle::from_static(module);

        assert!(!handle.supports_hot_reload());
    }

    #[test]
    fn test_static_module_save_state() {
        let module = HotReloadModule { counter: 12345 };
        let handle = ModuleHandle::from_static(module);

        let state = handle.save_state();
        assert!(state.is_some());

        let state = state.unwrap();
        assert_eq!(state.len(), 4);
        assert_eq!(u32::from_le_bytes([state[0], state[1], state[2], state[3]]), 12345);
    }

    #[test]
    fn test_static_module_restore_state() {
        let module = HotReloadModule { counter: 0 };
        let mut handle = ModuleHandle::from_static(module);

        // Create state representing counter = 99999
        let state: Box<[u8]> = 99999_u32.to_le_bytes().to_vec().into_boxed_slice();
        let result = handle.restore_state(&state);

        assert!(result.is_ok());

        // Verify by saving state again
        let saved = handle.save_state().unwrap();
        assert_eq!(u32::from_le_bytes([saved[0], saved[1], saved[2], saved[3]]), 99999);
    }

    #[test]
    fn test_static_module_restore_invalid_state() {
        let module = HotReloadModule { counter: 42 };
        let mut handle = ModuleHandle::from_static(module);

        // Wrong size state
        let invalid_state: Box<[u8]> = vec![1, 2, 3].into_boxed_slice();
        let result = handle.restore_state(&invalid_state);

        assert!(result.is_err());
    }

    #[test]
    fn test_static_module_full_reload_cycle() {
        // Simulate a full hot reload cycle:
        // 1. Module running with state
        // 2. Save state
        // 3. "Unload" (drop old handle)
        // 4. "Load" (create new handle)
        // 5. Restore state

        // Step 1: Original module with state
        let module = HotReloadModule { counter: 777 };
        let handle = ModuleHandle::from_static(module);

        // Step 2: Save state
        let saved_state = handle.save_state().unwrap();

        // Step 3: "Unload" - drop the handle
        drop(handle);

        // Step 4: "Load" new module (simulating reload)
        let new_module = HotReloadModule { counter: 0 };
        let mut new_handle = ModuleHandle::from_static(new_module);

        // Step 5: Restore state
        let result = new_handle.restore_state(&saved_state);
        assert!(result.is_ok());

        // Verify state was restored
        let final_state = new_handle.save_state().unwrap();
        assert_eq!(
            u32::from_le_bytes([
                final_state[0],
                final_state[1],
                final_state[2],
                final_state[3]
            ]),
            777
        );
    }

    #[test]
    fn test_module_without_hot_reload_save_state() {
        let module = TestModule { initialized: false };
        let handle = ModuleHandle::from_static(module);

        // Module doesn't support hot reload, save_state returns None
        let state = handle.save_state();
        assert!(state.is_none());
    }

    #[test]
    fn test_state_size_limit_constant() {
        // Verify the size limit is set to 16 MiB
        assert_eq!(MAX_STATE_SIZE, 16 * 1024 * 1024);
    }

    /// Test module that returns oversized state for testing size limits.
    struct OversizedStateModule;

    impl Module for OversizedStateModule {
        fn id(&self) -> ModuleId {
            ModuleId::new("oversized-state-module")
        }

        fn name(&self) -> &'static str {
            "Oversized State Module"
        }

        fn version(&self) -> Version {
            Version::new(1, 0, 0)
        }

        fn init(&mut self, _ctx: &ModuleContext) -> ProbeResult {
            ProbeResult::Success
        }

        fn exit(&mut self) -> Result<(), ModuleError> {
            Ok(())
        }

        fn supports_hot_reload(&self) -> bool {
            true
        }

        fn save_state(&self) -> Option<Box<[u8]>> {
            // Return state larger than MAX_STATE_SIZE (16 MiB + 1 byte)
            // Note: This test is expensive in memory, so we use a smaller test size
            // In real code, the limit is 16 MiB
            Some(vec![0u8; MAX_STATE_SIZE + 1].into_boxed_slice())
        }

        fn restore_state(&mut self, _state: &[u8]) -> Result<(), ModuleError> {
            Ok(())
        }
    }

    #[test]
    #[ignore = "expensive test - allocates 16+ MiB"]
    fn test_state_size_limit_enforced() {
        let module = OversizedStateModule;
        let handle = ModuleHandle::from_static(module);

        // Should return None because state exceeds size limit
        let state = handle.save_state();
        assert!(state.is_none());
    }
}
