//! Module handle for loaded modules.
//!
//! Provides a unified interface for both static and dynamic modules.

use std::{
    ffi::c_void,
    path::{Path, PathBuf},
};

use {
    libloading::Library,
    reovim_kernel::api::v1::{
        Module, ModuleContext, ModuleError, ModuleId, ModuleProbe, ProbeResult, Version,
    },
};

/// FFI function types from `declare_module!` macro.
///
/// These match the symbols generated by the kernel's proc-macro.
pub(crate) type ProbeFn = unsafe extern "C" fn() -> ModuleProbe;
pub(crate) type EntryFn = unsafe extern "C" fn() -> *mut c_void;
pub(crate) type InitFn = unsafe extern "C" fn(*mut c_void, *const c_void) -> i32;
pub(crate) type ExitFn = unsafe extern "C" fn(*mut c_void) -> i32;
pub(crate) type DestroyFn = unsafe extern "C" fn(*mut c_void);

/// Handle to a loaded module.
///
/// # FFI Safety
///
/// For dynamic modules, we keep opaque pointers (`*mut c_void`) instead of
/// `Box<dyn Module>` because fat pointers cannot cross FFI boundaries.
/// All lifecycle operations go through FFI trampolines.
pub struct ModuleHandle {
    /// Unique identifier (from probe).
    id: ModuleId,

    /// Module metadata (from probe, no allocation).
    probe: ModuleProbe,

    /// For STATIC modules: owned Box.
    static_module: Option<Box<dyn Module>>,

    /// For DYNAMIC modules: opaque pointer (FFI).
    dynamic_ptr: Option<*mut c_void>,

    /// Library handle (keeps .so loaded).
    library: Option<Library>,

    /// Source path (for hot reload).
    path: Option<PathBuf>,

    /// Cached FFI symbols (avoids repeated lookup).
    ffi: Option<FfiSymbols>,
}

// Safety: ModuleHandle is Send+Sync because:
// - static_module is Send+Sync (Module trait requires it)
// - dynamic_ptr is only accessed through FFI trampolines
// - Library handle is thread-safe for keeping library loaded
unsafe impl Send for ModuleHandle {}
unsafe impl Sync for ModuleHandle {}

/// Cached FFI symbols for dynamic modules.
pub(crate) struct FfiSymbols {
    pub(crate) init: InitFn,
    pub(crate) exit: ExitFn,
    pub(crate) destroy: DestroyFn,
}

/// Result of `init()` call.
#[derive(Debug, Clone)]
pub enum InitResult {
    /// Module initialized successfully.
    Success,
    /// Module deferred initialization (retry later).
    Defer(String),
}

impl ModuleHandle {
    /// Create a handle for a static (compile-time linked) module.
    pub fn from_static<M: Module>(module: M) -> Self {
        let probe = ModuleProbe::new(
            module.id().as_str(),
            module.name(),
            module.version(),
            module.api_version(),
        );
        let id = module.id();

        Self {
            id,
            probe,
            static_module: Some(Box::new(module)),
            dynamic_ptr: None,
            library: None,
            path: None,
            ffi: None,
        }
    }

    /// Create a handle for a dynamic (runtime loaded) module.
    ///
    /// # Safety
    ///
    /// - The library must be ABI-compatible
    /// - The library must have been built with matching `declare_module!` macro
    pub(crate) unsafe fn from_dynamic(
        library: Library,
        path: PathBuf,
        probe: ModuleProbe,
        module_ptr: *mut c_void,
        ffi: FfiSymbols,
    ) -> Self {
        let id = ModuleId::from_string(probe.id_str().to_owned());

        Self {
            id,
            probe,
            static_module: None,
            dynamic_ptr: Some(module_ptr),
            library: Some(library),
            path: Some(path),
            ffi: Some(ffi),
        }
    }

    /// Initialize the module via FFI trampoline.
    ///
    /// # FFI Return codes
    ///
    /// - `0` = Success (`ProbeResult::Success`)
    /// - `1` = Defer (`ProbeResult::Defer`) - retry later
    /// - `-1` = Failed (`ProbeResult::Failed`)
    /// - `-2` = Panic occurred
    pub fn init(&mut self, ctx: &ModuleContext) -> Result<InitResult, ModuleError> {
        if let Some(ref mut module) = self.static_module {
            // Static module: direct call
            match module.init(ctx) {
                ProbeResult::Success => Ok(InitResult::Success),
                ProbeResult::Defer(reason) => Ok(InitResult::Defer(reason)),
                ProbeResult::Failed(err) => Err(err),
            }
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            if ptr.is_null() {
                return Err(ModuleError::InitFailed("module pointer is null".into()));
            }

            // Dynamic module: FFI trampoline
            // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
            let ctx_ptr = ctx as *const ModuleContext as *const c_void;
            let result = unsafe { (ffi.init)(ptr, ctx_ptr) };

            match result {
                0 => Ok(InitResult::Success),
                1 => Ok(InitResult::Defer("deferred by module".into())),
                -1 => Err(ModuleError::InitFailed("init returned error".into())),
                -2 => Err(ModuleError::InitFailed("panic in module init".into())),
                code => Err(ModuleError::InitFailed(format!("unknown code: {code}"))),
            }
        } else {
            Err(ModuleError::NotLoaded(self.id.clone()))
        }
    }

    /// Call module exit via FFI trampoline.
    pub fn exit(&mut self) -> Result<(), ModuleError> {
        if let Some(ref mut module) = self.static_module {
            module.exit()
        } else if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr, &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            if ptr.is_null() {
                return Err(ModuleError::InitFailed("module pointer is null".into()));
            }

            // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
            let result = unsafe { (ffi.exit)(ptr) };
            match result {
                0 => Ok(()),
                -1 => Err(ModuleError::InitFailed("exit returned error".into())),
                -2 => Err(ModuleError::InitFailed("panic in module exit".into())),
                code => Err(ModuleError::InitFailed(format!("unknown code: {code}"))),
            }
        } else {
            Err(ModuleError::NotLoaded(self.id.clone()))
        }
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Get module ID.
    #[must_use]
    pub fn id(&self) -> &ModuleId {
        &self.id
    }

    /// Get module name from probe.
    #[must_use]
    pub fn name(&self) -> &str {
        self.probe.name_str()
    }

    /// Get module version from probe.
    #[must_use]
    pub fn version(&self) -> Version {
        self.probe.version
    }

    /// Get module API version from probe.
    #[must_use]
    pub fn api_version(&self) -> Version {
        self.probe.api_version
    }

    /// Get module path (for dynamic modules).
    #[must_use]
    pub fn path(&self) -> Option<&Path> {
        self.path.as_deref()
    }

    /// Check if this is a static module.
    #[must_use]
    pub fn is_static(&self) -> bool {
        self.static_module.is_some()
    }

    /// Check if this is a dynamic module.
    #[must_use]
    pub fn is_dynamic(&self) -> bool {
        self.dynamic_ptr.is_some()
    }

    /// Get static module reference (for static modules only).
    #[must_use]
    pub fn as_module(&self) -> Option<&dyn Module> {
        self.static_module.as_deref()
    }

    /// Get mutable static module reference.
    #[must_use]
    pub fn as_module_mut(&mut self) -> Option<&mut dyn Module> {
        self.static_module.as_deref_mut()
    }

    /// Get module dependencies.
    #[must_use]
    pub fn dependencies(&self) -> Vec<ModuleId> {
        if let Some(ref module) = self.static_module {
            module.dependencies()
        } else {
            // For dynamic modules, we'd need FFI trampolines
            // For now, return empty (dependencies should be in probe metadata)
            Vec::new()
        }
    }

    /// Get optional dependencies.
    #[must_use]
    pub fn optional_dependencies(&self) -> Vec<ModuleId> {
        if let Some(ref module) = self.static_module {
            module.optional_dependencies()
        } else {
            Vec::new()
        }
    }

    /// Check if module supports hot reload.
    #[must_use]
    pub fn supports_hot_reload(&self) -> bool {
        if let Some(ref module) = self.static_module {
            module.supports_hot_reload()
        } else {
            // Dynamic modules: assume supported (caller checks FFI)
            false
        }
    }

    /// Save module state (for hot reload).
    #[must_use]
    pub fn save_state(&self) -> Option<Box<[u8]>> {
        if let Some(ref module) = self.static_module {
            module.save_state()
        } else {
            // Dynamic modules: would need FFI trampoline (future kernel extension)
            None
        }
    }

    /// Restore module state (for hot reload).
    pub fn restore_state(&mut self, state: &[u8]) -> Result<(), ModuleError> {
        if let Some(ref mut module) = self.static_module {
            module.restore_state(state)
        } else {
            // Dynamic modules: would need FFI trampoline (future kernel extension)
            Err(ModuleError::InitFailed(
                "state restore not supported for dynamic modules".into(),
            ))
        }
    }
}

impl Drop for ModuleHandle {
    fn drop(&mut self) {
        // For dynamic modules: call destroy trampoline
        if let (Some(ptr), Some(ffi)) = (self.dynamic_ptr.take(), &self.ffi) {
            // Safety: Validate pointer before FFI call (defense-in-depth)
            // Note: proc-macro's destroy also checks for null, but we check here too
            if !ptr.is_null() {
                // SAFETY: ptr is non-null (checked above), ffi symbols are valid (from loader)
                unsafe { (ffi.destroy)(ptr) };
            }
        }
        // Library is dropped automatically, unloading the .so
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestModule {
        initialized: bool,
    }

    impl Module for TestModule {
        fn id(&self) -> ModuleId {
            ModuleId::new("test-module")
        }

        fn name(&self) -> &'static str {
            "Test Module"
        }

        fn version(&self) -> Version {
            Version::new(1, 0, 0)
        }

        fn init(&mut self, _ctx: &ModuleContext) -> ProbeResult {
            self.initialized = true;
            ProbeResult::Success
        }

        fn exit(&mut self) -> Result<(), ModuleError> {
            self.initialized = false;
            Ok(())
        }
    }

    #[test]
    fn test_static_handle_creation() {
        let module = TestModule { initialized: false };
        let handle = ModuleHandle::from_static(module);

        assert!(handle.is_static());
        assert!(!handle.is_dynamic());
        assert_eq!(handle.id().as_str(), "test-module");
        assert_eq!(handle.name(), "Test Module");
    }

    #[test]
    fn test_static_handle_init() {
        let module = TestModule { initialized: false };
        let mut handle = ModuleHandle::from_static(module);
        let ctx = ModuleContext::default();

        let result = handle.init(&ctx);
        assert!(matches!(result, Ok(InitResult::Success)));
    }

    #[test]
    fn test_static_handle_exit() {
        let module = TestModule { initialized: true };
        let mut handle = ModuleHandle::from_static(module);

        let result = handle.exit();
        assert!(result.is_ok());
    }
}
