[package]
name = "reovim-subsys-command"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Command subsystem contracts for reovim (command framework)"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
reovim-kernel = { workspace = true }
reovim-subsys-command-types = { workspace = true }
