[package]
name = "reovim-module-git-statusline"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Git statusline branch component for reovim"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
dynamic = []

[dependencies]
reovim-kernel = { workspace = true }
reovim-subsys-git = { workspace = true }
reovim-subsys-statusline = { workspace = true }
reovim-module-macros = { workspace = true }

[lints]
workspace = true
