//! Resolved-graph sovereignty gate (spec 1.2 §5 / §9).
//!
//! The live test reads the real `Cargo.lock` and asserts every
//! `[[package]]` entry is workspace-local: no `source = "registry+..."`,
//! no `source = "git+..."`.
//!
//! Fixture tests exercise the parse helper directly with inline TOML text.

mod common;

// ── lockfile parser (test-only; must NOT be added to src/lib.rs) ─────────────

/// A `[[package]]` entry parsed from `Cargo.lock`.
#[derive(Debug, PartialEq, Eq)]
struct LockPackage {
    name: String,
    /// `source` field if present. Absent for workspace-local packages.
    source: Option<String>,
}

/// Parses `[[package]]` blocks from `Cargo.lock` text.
///
/// Only `name` and `source` fields are extracted. The parser is line-oriented
/// and intentionally minimal (std-only, no third-party crates).
///
/// Malformed lines are silently skipped (this is a test helper).
#[must_use]
fn parse_lockfile(text: &str) -> Vec<LockPackage> {
    let mut packages: Vec<LockPackage> = Vec::new();
    let mut current: Option<LockPackage> = None;

    for line in text.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            if let Some(pkg) = current.take() {
                packages.push(pkg);
            }
            current = Some(LockPackage {
                name: String::new(),
                source: None,
            });
        } else if let Some(ref mut pkg) = current {
            if let Some(rest) = line.strip_prefix("name = ") {
                rest.trim_matches('"').clone_into(&mut pkg.name);
            } else if let Some(rest) = line.strip_prefix("source = ") {
                pkg.source = Some(rest.trim_matches('"').to_owned());
            }
        }
    }
    if let Some(pkg) = current {
        packages.push(pkg);
    }
    packages
}

/// Returns the packages in `packages` whose `source` is external
/// (registry or git). An absent `source` means workspace-local.
#[must_use]
fn external_packages(packages: &[LockPackage]) -> Vec<&LockPackage> {
    packages
        .iter()
        .filter(|p| {
            p.source
                .as_deref()
                .is_some_and(|s| s.starts_with("registry+") || s.starts_with("git+"))
        })
        .collect()
}

// ── live gate ─────────────────────────────────────────────────────────────────

/// DAG5 resolved-graph gate: every `[[package]]` in `Cargo.lock` must be
/// workspace-local. Any `source = "registry+..."` or `source = "git+..."`
/// entry is a sovereignty violation.
///
/// The gate fails **closed**: if `Cargo.lock` is missing the test fails with
/// a clear message (the workspace MUST be lockfile-present for this gate to
/// be meaningful).
#[test]
fn live_lockfile_is_workspace_local() {
    let root = common::workspace_root();
    let lockfile = root.join("Cargo.lock");
    assert!(
        lockfile.exists(),
        "Cargo.lock not found at `{}`; the sovereignty gate requires a committed \
         lockfile — run `cargo generate-lockfile` and commit it",
        lockfile.display()
    );
    let text = std::fs::read_to_string(&lockfile)
        .unwrap_or_else(|e| panic!("cannot read `{}`: {e}", lockfile.display()));
    let packages = parse_lockfile(&text);
    assert!(
        !packages.is_empty(),
        "Cargo.lock parsed zero [[package]] blocks — file may be corrupt or \
         use an unsupported format version"
    );
    let external = external_packages(&packages);
    assert!(
        external.is_empty(),
        "DAG5 sovereignty violation: Cargo.lock contains {} external package(s):\n{}",
        external.len(),
        external
            .iter()
            .map(|p| format!("  {} (source: {})", p.name, p.source.as_deref().unwrap_or("?")))
            .collect::<Vec<_>>()
            .join("\n")
    );
}

// ── fixture tests ─────────────────────────────────────────────────────────────

/// A `Cargo.lock` text with one registry-sourced package → the parse helper
/// must detect it as external and the gate helper must flag it.
const REGISTRY_LOCKFILE: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "reovim-depgraph"
version = "0.16.0-dev"

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"
"#;

#[test]
fn registry_source_fails() {
    let packages = parse_lockfile(REGISTRY_LOCKFILE);
    // Two packages should parse.
    assert_eq!(packages.len(), 2, "expected 2 packages, got {packages:?}");

    let external = external_packages(&packages);
    assert_eq!(external.len(), 1, "expected 1 external package (serde), got {external:?}");
    assert_eq!(external[0].name, "serde");
    assert!(
        external[0]
            .source
            .as_deref()
            .unwrap_or("")
            .starts_with("registry+"),
        "source should start with registry+; got {:?}",
        external[0].source
    );
}

/// An all-local `Cargo.lock` (no `source` fields) → the gate reports zero
/// external packages.
const LOCAL_LOCKFILE: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "reovim-depgraph"
version = "0.16.0-dev"

[[package]]
name = "reovim-arch"
version = "0.16.0-dev"
"#;

#[test]
fn all_local_passes() {
    let packages = parse_lockfile(LOCAL_LOCKFILE);
    assert_eq!(packages.len(), 2, "expected 2 packages, got {packages:?}");
    let external = external_packages(&packages);
    assert!(
        external.is_empty(),
        "all-local lockfile must produce zero external packages; got {external:?}"
    );
}

/// A lockfile with a git-sourced package → also detected as external.
const GIT_LOCKFILE: &str = r#"
version = 4

[[package]]
name = "reovim-depgraph"
version = "0.16.0-dev"

[[package]]
name = "some-git-dep"
version = "0.1.0"
source = "git+https://github.com/example/some-git-dep?rev=abc123"
"#;

#[test]
fn git_source_fails() {
    let packages = parse_lockfile(GIT_LOCKFILE);
    let external = external_packages(&packages);
    assert_eq!(external.len(), 1, "expected 1 external git package; got {external:?}");
    assert_eq!(external[0].name, "some-git-dep");
}
